import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class ApiGatewayAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      cors?: { origins?: string[]; methods?: string[] };
      stage?: string;
    };

    const integratesLambda = this.dependencies.includes("lambda");
    if (integratesLambda) {
      await this.waitFor("lambda", "functionArn");
      await this.waitFor("lambda", "functionName");
    }

    const corsOrigins = JSON.stringify(cfg.cors?.origins ?? ["*"]);
    const corsMethods = JSON.stringify(cfg.cors?.methods ?? ["GET", "POST", "PUT", "DELETE", "OPTIONS"]);
    const stageName = cfg.stage ?? "$default";

    const lambdaIntegration = integratesLambda
      ? `resource "aws_apigatewayv2_integration" "lambda" {
  api_id                 = aws_apigatewayv2_api.main.id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.app.arn
  integration_method     = "POST"
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "default" {
  api_id    = aws_apigatewayv2_api.main.id
  route_key = "$default"
  target    = "integrations/\${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_lambda_permission" "apigw" {
  statement_id  = "AllowAPIGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.app.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "\${aws_apigatewayv2_api.main.execution_arn}/*/*"
}
`
      : `# No Lambda dependency — add routes manually or wire to ALB/NLB integration.
`;

    const tf = `# API Gateway (HTTP API) — Generated by Launch Platform
resource "aws_apigatewayv2_api" "main" {
  name          = "${projectName}-api"
  protocol_type = "HTTP"
  description   = "HTTP API for ${projectName}"

  cors_configuration {
    allow_origins = ${corsOrigins}
    allow_methods = ${corsMethods}
    allow_headers = ["*"]
    max_age       = 86400
  }
}

${lambdaIntegration}
resource "aws_apigatewayv2_stage" "main" {
  api_id      = aws_apigatewayv2_api.main.id
  name        = "${stageName}"
  auto_deploy = true

  default_route_settings {
    throttling_burst_limit = 5000
    throttling_rate_limit  = 10000
  }
}

output "api_id"           { value = aws_apigatewayv2_api.main.id }
output "api_endpoint"     { value = aws_apigatewayv2_api.main.api_endpoint }
output "api_execution_arn" { value = aws_apigatewayv2_api.main.execution_arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("apiId", "${aws_apigatewayv2_api.main.id}");
    this.publishOutput("apiEndpoint", "${aws_apigatewayv2_api.main.api_endpoint}");
  }

  protected async configure(): Promise<void> { this.log("API Gateway configured"); }
  protected async deploy(): Promise<void>   { this.log("API Gateway deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("API Gateway endpoint reachable"); }
  protected async doRollback(): Promise<void> { this.log("API Gateway rollback"); }
}
