import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

interface BqTable {
  tableId: string;
  schema?: object[];      // BigQuery JSON schema
  partitioning?: { type: "DAY" | "HOUR" | "MONTH"; field?: string };
}

export class BigQueryAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const region = this.context.plan.region;
    const cfg = this.context.recommendation.config as {
      datasetId?: string;
      description?: string;
      tables?: BqTable[];
      defaultTableExpirationMs?: number;
    };

    const datasetId = cfg.datasetId ?? projectName.replace(/-/g, "_");
    const description = cfg.description ?? `Dataset for ${projectName}`;
    const tables = cfg.tables ?? [];
    const expirationMs = cfg.defaultTableExpirationMs;

    const tableBlocks = tables.map((t, i) => `resource "google_bigquery_table" "t_${i}" {
  project    = "${projectId}"
  dataset_id = google_bigquery_dataset.main.dataset_id
  table_id   = "${t.tableId}"

  ${t.partitioning ? `time_partitioning {
    type  = "${t.partitioning.type}"
    ${t.partitioning.field ? `field = "${t.partitioning.field}"` : ""}
  }` : ""}

  schema = jsonencode(${JSON.stringify(t.schema ?? [], null, 2).replace(/\n/g, "\n    ")})

  deletion_protection = false
}`).join("\n\n");

    const tf = `# BigQuery — Generated by Launch Platform
resource "google_bigquery_dataset" "main" {
  project     = "${projectId}"
  dataset_id  = "${datasetId}"
  description = "${description}"
  location    = "${region.startsWith("us") ? "US" : region.startsWith("europe") ? "EU" : region}"
  ${expirationMs ? `default_table_expiration_ms = ${expirationMs}` : ""}

  labels = {
    project = "${projectName}"
  }
}

${tableBlocks}

output "dataset_id" { value = google_bigquery_dataset.main.dataset_id }
output "dataset_url" { value = "https://console.cloud.google.com/bigquery?project=${projectId}&d=\${google_bigquery_dataset.main.dataset_id}" }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("datasetId", "${google_bigquery_dataset.main.dataset_id}");
  }

  protected async configure(): Promise<void> { this.log("BigQuery configured"); }
  protected async deploy(): Promise<void>   { this.log("BigQuery deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("BigQuery dataset accessible"); }
  protected async doRollback(): Promise<void> { this.log("BigQuery rollback"); }
}
