import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudIAMAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# GCP IAM — Generated by SASA Launch
resource "google_service_account" "app" {
  account_id   = "${projectName}-app-sa"
  display_name = "${projectName} Application Service Account"
  project      = "${projectId}"
}

resource "google_service_account" "cloud_run" {
  account_id   = "${projectName}-run-sa"
  display_name = "${projectName} Cloud Run Service Account"
  project      = "${projectId}"
}

resource "google_project_iam_member" "cloud_run_invoker" {
  project = "${projectId}"
  role    = "roles/run.invoker"
  member  = "serviceAccount:\${google_service_account.cloud_run.email}"
}

resource "google_project_iam_member" "cloud_sql_client" {
  project = "${projectId}"
  role    = "roles/cloudsql.client"
  member  = "serviceAccount:\${google_service_account.app.email}"
}

resource "google_project_iam_member" "storage_admin" {
  project = "${projectId}"
  role    = "roles/storage.objectAdmin"
  member  = "serviceAccount:\${google_service_account.app.email}"
}

resource "google_project_iam_member" "secret_accessor" {
  project = "${projectId}"
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:\${google_service_account.app.email}"
}

resource "google_project_iam_member" "log_writer" {
  project = "${projectId}"
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:\${google_service_account.app.email}"
}

output "app_service_account_email" { value = google_service_account.app.email }
output "cloud_run_service_account_email" { value = google_service_account.cloud_run.email }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("appServiceAccountEmail", "${google_service_account.app.email}");
    this.publishOutput("cloudRunServiceAccountEmail", "${google_service_account.cloud_run.email}");
  }

  protected async configure(): Promise<void> { this.log("IAM roles configured"); }
  protected async deploy(): Promise<void> { this.log("IAM deployed via Terraform"); }
  protected async validate(): Promise<void> { this.log("IAM service accounts validated"); }
  protected async doRollback(): Promise<void> { this.log("IAM rollback: terraform destroy"); }
}
