import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class ECRAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();

    const tf = `# ECR — Generated by SASA Launch
resource "aws_ecr_repository" "app" {
  name                 = "${projectName}-app"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  encryption_configuration {
    encryption_type = "AES256"
  }
}

resource "aws_ecr_lifecycle_policy" "app" {
  repository = aws_ecr_repository.app.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Keep last 10 images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 10
      }
      action = { type = "expire" }
    }]
  })
}

output "repository_url" { value = aws_ecr_repository.app.repository_url }
output "repository_arn" { value = aws_ecr_repository.app.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("repositoryUrl", "$\{aws_ecr_repository.app.repository_url}");
    this.publishOutput("repositoryArn", "$\{aws_ecr_repository.app.arn}");
  }

  protected async configure(): Promise<void> { this.log("ECR configured"); }
  protected async deploy(): Promise<void> { this.log("ECR: docker push"); }
  protected async validate(): Promise<void> { this.log("ECR repository accessible"); }
  protected async doRollback(): Promise<void> { this.log("ECR rollback"); }
}
