import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class MemorystoreAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc-gcp", "networkName");
    const projectName = this.getProjectName();
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Memorystore Redis — Generated by SASA Launch
resource "google_redis_instance" "main" {
  name               = "${projectName}-redis"
  tier               = "BASIC"
  memory_size_gb     = 1
  region             = "${region}"
  project            = "${projectId}"
  authorized_network = var.network_id
  redis_version      = "REDIS_7_0"

  display_name = "${projectName} Redis Cache"
}

variable "network_id" { type = string }

output "host" { value = google_redis_instance.main.host }
output "port" { value = google_redis_instance.main.port }
output "redis_url" { value = "redis://\${google_redis_instance.main.host}:\${google_redis_instance.main.port}" }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("host", "${google_redis_instance.main.host}");
    this.publishOutput("port", "${google_redis_instance.main.port}");
  }

  protected async configure(): Promise<void> { this.log("Memorystore configured"); }
  protected async deploy(): Promise<void> { this.log("Memorystore ready"); }
  protected async validate(): Promise<void> { this.log("Memorystore connectivity check"); }
  protected async doRollback(): Promise<void> { this.log("Memorystore rollback"); }
}
