import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { log } from "../utils/logger.js";

export class ArtifactWriter {
  private baseDir: string;
  private files: { path: string; content: string }[] = [];

  constructor(workDir: string) {
    this.baseDir = join(workDir, "artifacts");
    mkdirSync(this.baseDir, { recursive: true });
  }

  write(relativePath: string, content: string): string {
    const fullPath = join(this.baseDir, relativePath);
    const dir = dirname(fullPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, content);
    this.files.push({ path: relativePath, content });
    log.debug(`Wrote artifact: ${relativePath}`);
    return fullPath;
  }

  writeTerraform(provider: string, service: string, filename: string, content: string): string {
    return this.write(join("terraform", provider, service, filename), content);
  }

  writeDocker(filename: string, content: string): string {
    return this.write(join("docker", filename), content);
  }

  writeScript(filename: string, content: string): string {
    return this.write(join("scripts", filename), content);
  }

  writeProviderConfig(provider: string, region: string): string {
    if (provider === "aws") {
      const content = `# AWS Provider Configuration — Generated by Launch Platform
terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "${region}"
  default_tags {
    tags = {
      ManagedBy = "launch-platform"
      CreatedAt = "${new Date().toISOString()}"
    }
  }
}
`;
      return this.writeTerraform("aws", "_provider", "main.tf", content);
    }
    return "";
  }

  getFiles(): { path: string; content: string }[] {
    return [...this.files];
  }

  getBaseDir(): string {
    return this.baseDir;
  }
}
