import type { DeploymentPlan } from "../types/plan.js";
import type { ServiceRecommendation } from "../types/cloud.js";
import { DeploymentOrchestrator, type DeploymentResult } from "../agents/deployment-orchestrator.js";
import { ArtifactWriter } from "./artifact-writer.js";
import { isTerraformInstalled } from "./terraform.js";
import { log } from "../utils/logger.js";
import { StateStore } from "../state/store.js";
import { ExecutionJournal } from "../state/journal.js";
import { ExecutionLock } from "../state/lock.js";

export async function executeDeployment(
  plan: DeploymentPlan,
  recommendations: ServiceRecommendation[]
): Promise<DeploymentResult> {
  // Acquire lock
  const lock = new ExecutionLock(plan.workDir);
  if (!lock.acquire()) {
    throw new Error("Another deployment is in progress. Check .launch/lock");
  }

  const state = new StateStore(plan.workDir);
  const journal = new ExecutionJournal(plan.workDir);

  try {
    // Write provider config
    const writer = new ArtifactWriter(plan.workDir);
    writer.writeProviderConfig(plan.provider, plan.region);
    log.info("Provider configuration written");

    // Generate deployment script
    writer.writeScript("deploy.sh", generateDeployScript(plan, recommendations));
    writer.writeScript("rollback.sh", generateRollbackScript(plan));
    log.info("Deployment scripts generated");

    // Check terraform if in apply mode
    if (plan.applyMode && !isTerraformInstalled()) {
      log.warn("Terraform not installed. Falling back to artifact-only mode.");
      plan.applyMode = false;
    }

    // Run orchestrator
    state.setPhase("deploying");
    journal.append({ type: "deployment:start", data: { provider: plan.provider, region: plan.region, services: recommendations.length } });

    const orchestrator = new DeploymentOrchestrator(plan, recommendations);
    const result = await orchestrator.execute();

    if (result.success) {
      state.setPhase("complete");
      state.markComplete();
      journal.append({ type: "deployment:complete", data: { duration: result.totalDuration } });
    } else {
      state.setPhase("failed");
      journal.append({ type: "deployment:failed", data: { error: result.error } });

      // Offer rollback in apply mode
      if (plan.applyMode) {
        log.warn("Deployment failed. Rolling back...");
        await orchestrator.rollback();
      }
    }

    // Write summary
    const summaryPath = writer.write("summary.json", JSON.stringify({
      plan: { provider: plan.provider, region: plan.region, applyMode: plan.applyMode },
      services: recommendations.map(r => ({ id: r.serviceId, name: r.serviceName, reason: r.reason })),
      result: { success: result.success, duration: result.totalDuration, error: result.error },
      artifacts: writer.getFiles().map(f => f.path),
      timestamp: new Date().toISOString(),
    }, null, 2));
    log.info(`Summary written to ${summaryPath}`);

    return result;
  } finally {
    lock.release();
  }
}

function generateDeployScript(plan: DeploymentPlan, recs: ServiceRecommendation[]): string {
  const services = recs.map(r => r.serviceId);
  return `#!/bin/bash
# Deploy script — Generated by Launch Platform
# Provider: ${plan.provider} | Region: ${plan.region}
set -euo pipefail

echo "=== Launch Platform Deployment ==="
echo "Provider: ${plan.provider}"
echo "Region: ${plan.region}"
echo "Services: ${services.join(", ")}"
echo ""

ARTIFACT_DIR="$(dirname "$0")/../terraform/${plan.provider}"

# Initialize and apply each service module
${services.map(s => `
echo "--- Deploying ${s} ---"
if [ -d "$ARTIFACT_DIR/${s}" ]; then
  cd "$ARTIFACT_DIR/${s}"
  terraform init -input=false
  terraform apply -auto-approve -input=false
  cd -
fi`).join("\n")}

echo ""
echo "=== Deployment Complete ==="
`;
}

function generateRollbackScript(plan: DeploymentPlan): string {
  return `#!/bin/bash
# Rollback script — Generated by Launch Platform
set -euo pipefail

echo "=== Launch Platform Rollback ==="
ARTIFACT_DIR="$(dirname "$0")/../terraform/${plan.provider}"

for dir in "$ARTIFACT_DIR"/*/; do
  if [ -f "$dir/main.tf" ]; then
    echo "--- Rolling back $(basename "$dir") ---"
    cd "$dir"
    terraform destroy -auto-approve -input=false || true
    cd -
  fi
done

echo "=== Rollback Complete ==="
`;
}
