/**
 * Agent template — copy this file to <id>-agent.ts when adding a new agent.
 *
 * Checklist after copying:
 *   1. Implement provision() to write Terraform to <artifactDir>/main.tf
 *   2. Add the agent class to src/agents/agent-registry.ts (right map: AWS or GCP)
 *   3. Add an inference rule in src/inference/rules/ (or extend existing one)
 *      so the orchestrator recommends this service
 *   4. Add a daily-cost entry to src/monitoring/collectors/cost.ts
 *   5. Add a cost entry to web/components/ServiceGrid.tsx COSTS map
 *   6. Run `npm run smoke -- --agent <id>` to verify terraform validates
 *
 * See docs/contributing/adding-an-agent.md for the full walkthrough.
 */

import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class TemplateAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    // 1. Wait for any upstream services this agent depends on. The orchestrator
    //    enforces topological order via recommendation.dependsOn, but waitFor
    //    blocks until the upstream agent has actually published the output.
    //
    //    Example:
    //    const vpcId = await this.waitFor("vpc", "vpcId");
    //    Then reference in TF: subnet_id = ${JSON.stringify(vpcId)}
    //
    //    The interpolation string `${aws_vpc.main.id}` resolves at
    //    `terraform apply` time because all per-agent .tf files are merged
    //    into one stack by the orchestrator.

    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      // Declare per-agent config knobs here. Inference engine populates these
      // when it creates the recommendation. Users can override from the UI.
      mySetting?: string;
    };

    // 2. Build the terraform body. Keep production-ready defaults; let users
    //    override via cfg.* fields. Avoid hardcoding values that would block
    //    real deployments (e.g. instance types, region-specific AMIs).
    const tf = `# Template — Generated by Launch Platform
resource "aws_xxx" "main" {
  name = "${projectName}-thing"

  # ... your resources here
}

output "thing_id" { value = aws_xxx.main.id }
`;

    // 3. Write the .tf file. The orchestrator merges all per-agent main.tf
    //    files into a single root before running terraform apply.
    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);

    // 4. Publish outputs that downstream agents may waitFor. Use Terraform
    //    interpolation strings — they resolve at apply time in the merged stack.
    this.publishOutput("thingId", "${aws_xxx.main.id}");
  }

  protected async configure(): Promise<void> {
    this.log("Template configured");
  }

  protected async deploy(): Promise<void> {
    // The orchestrator runs terraform apply once across the merged stack
    // after all provision/configure phases. Per-agent deploy() is for
    // post-apply work (e.g. cache warm-up, health-check ping).
    this.log("Template deploys via terraform apply");
  }

  protected async validate(): Promise<void> {
    // Real validation belongs here — e.g. HTTP probe, version check.
    this.log("Template ready");
  }

  protected async doRollback(): Promise<void> {
    this.log("Template rollback (terraform destroy via base class)");
  }

  // Override stop()/start() if your service supports a pause / scale-to-zero
  // pattern. Otherwise base-class returns "unsupported" and the user can
  // only call destroy().
  //
  // async stop() { /* set scale-to-zero, return ProvisionResult */ }
  // async start() { /* restore */ }
}
