import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class ArtifactRegistryAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.context.plan.source.split("/").pop()?.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase() || "launch";
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Artifact Registry — Generated by SASA Launch
resource "google_artifact_registry_repository" "app" {
  location      = "${region}"
  repository_id = "${projectName}-repo"
  description   = "Docker repository for ${projectName}"
  format        = "DOCKER"
  project       = "${projectId}"
}

output "repository_id" { value = google_artifact_registry_repository.app.repository_id }
output "repository_url" {
  value = "${region}-docker.pkg.dev/${projectId}/\${google_artifact_registry_repository.app.repository_id}"
}
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("repositoryId", "${google_artifact_registry_repository.app.repository_id}");
    this.publishOutput("repositoryUrl", `${region}-docker.pkg.dev/${projectId}/${projectName}-repo`);
  }

  protected async configure(): Promise<void> { this.log("Artifact Registry configured"); }
  protected async deploy(): Promise<void> { this.log("Artifact Registry: docker push"); }
  protected async validate(): Promise<void> { this.log("Artifact Registry accessible"); }
  protected async doRollback(): Promise<void> { this.log("Artifact Registry rollback"); }
}
