import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudFrontAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.context.plan.source.split("/").pop() || "launch";

    const tf = `# CloudFront Configuration — Generated by Launch Platform
resource "aws_cloudfront_distribution" "main" {
  enabled             = true
  default_root_object = "index.html"
  price_class         = "PriceClass_100"

  origin {
    domain_name = var.origin_domain
    origin_id   = "${projectName}-origin"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "${projectName}-origin"
    viewer_protocol_policy = "redirect-to-https"

    forwarded_values {
      query_string = true
      cookies { forward = "none" }
    }
  }

  restrictions {
    geo_restriction { restriction_type = "none" }
  }

  viewer_certificate { cloudfront_default_certificate = true }

  tags = { Name = "${projectName}-cdn" }
}

variable "origin_domain" { type = string }

output "distribution_id" { value = aws_cloudfront_distribution.main.id }
output "domain_name" { value = aws_cloudfront_distribution.main.domain_name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("distributionId", "${aws_cloudfront_distribution.main.id}");
    this.publishOutput("domainName", "${aws_cloudfront_distribution.main.domain_name}");
  }

  protected async configure(): Promise<void> { this.log("CloudFront configured"); }
  protected async deploy(): Promise<void> { this.log("CloudFront cache invalidation"); }
  protected async validate(): Promise<void> { this.log("CloudFront distribution active"); }
  protected async doRollback(): Promise<void> { this.log("CloudFront rollback"); }
}
