import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudFunctionsAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("cloud-iam", "appServiceAccountEmail");
    const projectName = this.context.plan.source.split("/").pop()?.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase() || "launch";
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Cloud Functions — Generated by SASA Launch
resource "google_storage_bucket" "function_source" {
  name     = "${projectId}-${projectName}-fn-source"
  location = "${region}"
  project  = "${projectId}"

  uniform_bucket_level_access = true
}

resource "google_cloudfunctions2_function" "app" {
  name     = "${projectName}-function"
  location = "${region}"
  project  = "${projectId}"

  build_config {
    runtime     = "nodejs20"
    entry_point = "handler"

    source {
      storage_source {
        bucket = google_storage_bucket.function_source.name
        object = "function-source.zip"
      }
    }
  }

  service_config {
    max_instance_count    = 10
    min_instance_count    = 0
    available_memory      = "256M"
    timeout_seconds       = 60
    service_account_email = var.service_account_email

    environment_variables = {
      NODE_ENV = "production"
    }
  }
}

resource "google_cloud_run_service_iam_member" "function_public" {
  location = google_cloudfunctions2_function.app.location
  project  = "${projectId}"
  service  = google_cloudfunctions2_function.app.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}

variable "service_account_email" { type = string }

output "function_uri" { value = google_cloudfunctions2_function.app.url }
output "function_name" { value = google_cloudfunctions2_function.app.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("functionUri", "${google_cloudfunctions2_function.app.url}");
    this.publishOutput("functionName", "${google_cloudfunctions2_function.app.name}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Function configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud Function deploying source"); }
  protected async validate(): Promise<void> { this.log("Cloud Function invocation test"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Function rollback"); }
}
