import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudMonitoringAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.context.plan.source.split("/").pop()?.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase() || "launch";
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Cloud Monitoring — Generated by SASA Launch
resource "google_monitoring_uptime_check_config" "app" {
  display_name = "${projectName}-uptime"
  project      = "${projectId}"
  timeout      = "10s"
  period       = "60s"

  http_check {
    path         = "/health"
    port         = 443
    use_ssl      = true
    validate_ssl = true
  }

  monitored_resource {
    type = "uptime_url"
    labels = {
      project_id = "${projectId}"
      host       = var.service_url
    }
  }
}

resource "google_monitoring_alert_policy" "high_cpu" {
  display_name = "${projectName} High CPU"
  project      = "${projectId}"
  combiner     = "OR"

  conditions {
    display_name = "CPU > 80%"
    condition_threshold {
      filter          = "metric.type=\\"compute.googleapis.com/instance/cpu/utilization\\" AND resource.type=\\"gce_instance\\""
      duration        = "300s"
      comparison      = "COMPARISON_GT"
      threshold_value = 0.8

      aggregations {
        alignment_period   = "60s"
        per_series_aligner = "ALIGN_MEAN"
      }
    }
  }

  notification_channels = []
}

resource "google_monitoring_alert_policy" "high_error_rate" {
  display_name = "${projectName} High Error Rate"
  project      = "${projectId}"
  combiner     = "OR"

  conditions {
    display_name = "Error rate > 5%"
    condition_threshold {
      filter          = "metric.type=\\"run.googleapis.com/request_count\\" AND resource.type=\\"cloud_run_revision\\" AND metric.labels.response_code_class!=\\"2xx\\""
      duration        = "300s"
      comparison      = "COMPARISON_GT"
      threshold_value = 5

      aggregations {
        alignment_period     = "60s"
        per_series_aligner   = "ALIGN_RATE"
        cross_series_reducer = "REDUCE_SUM"
      }
    }
  }

  notification_channels = []
}

resource "google_logging_metric" "app_errors" {
  name    = "${projectName}-error-count"
  project = "${projectId}"
  filter  = "resource.type=\\"cloud_run_revision\\" AND severity>=ERROR"

  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
  }
}

variable "service_url" { type = string; default = "example.com" }

output "uptime_check_id" { value = google_monitoring_uptime_check_config.app.uptime_check_id }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("uptimeCheckId", "${google_monitoring_uptime_check_config.app.uptime_check_id}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Monitoring configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud Monitoring active"); }
  protected async validate(): Promise<void> { this.log("Cloud Monitoring alerts verified"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Monitoring rollback"); }
}
