import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudCDNAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.context.plan.source.split("/").pop()?.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase() || "launch";
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Cloud CDN — Generated by SASA Launch
resource "google_compute_backend_bucket" "cdn" {
  name        = "${projectName}-cdn-backend"
  bucket_name = var.bucket_name
  enable_cdn  = true
  project     = "${projectId}"

  cdn_policy {
    cache_mode                   = "CACHE_ALL_STATIC"
    default_ttl                  = 3600
    max_ttl                      = 86400
    serve_while_stale            = 86400
    signed_url_cache_max_age_sec = 7200
  }
}

resource "google_compute_url_map" "cdn" {
  name            = "${projectName}-cdn-url-map"
  default_service = google_compute_backend_bucket.cdn.id
  project         = "${projectId}"
}

resource "google_compute_target_http_proxy" "cdn" {
  name    = "${projectName}-cdn-proxy"
  url_map = google_compute_url_map.cdn.id
  project = "${projectId}"
}

resource "google_compute_global_forwarding_rule" "cdn" {
  name       = "${projectName}-cdn-rule"
  target     = google_compute_target_http_proxy.cdn.id
  port_range = "80"
  project    = "${projectId}"
}

variable "bucket_name" { type = string }

output "cdn_ip" { value = google_compute_global_forwarding_rule.cdn.ip_address }
output "url_map_name" { value = google_compute_url_map.cdn.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("cdnIp", "${google_compute_global_forwarding_rule.cdn.ip_address}");
    this.publishOutput("urlMapName", "${google_compute_url_map.cdn.name}");
  }

  protected async configure(): Promise<void> { this.log("Cloud CDN configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud CDN cache invalidation"); }
  protected async validate(): Promise<void> { this.log("Cloud CDN distribution active"); }
  protected async doRollback(): Promise<void> { this.log("Cloud CDN rollback"); }
}
