import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class ECSAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc", "vpcId");
    await this.waitFor("iam", "ecsExecutionRoleArn");
    const projectName = this.getProjectName();

    const tf = `# ECS Fargate Configuration — Generated by Launch Platform
resource "aws_ecs_cluster" "main" {
  name = "${projectName}-cluster"
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

resource "aws_cloudwatch_log_group" "ecs" {
  name              = "/ecs/${projectName}"
  retention_in_days = 30
}

resource "aws_ecs_task_definition" "app" {
  family                   = "${projectName}-app"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn       = var.ecs_execution_role_arn
  task_role_arn            = var.ecs_task_role_arn

  container_definitions = jsonencode([{
    name      = "${projectName}-app"
    image     = var.container_image
    essential = true
    portMappings = [{ containerPort = 3000, protocol = "tcp" }]
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = "/ecs/${projectName}"
        "awslogs-region"        = var.region
        "awslogs-stream-prefix" = "app"
      }
    }
    environment = []
  }])
}

resource "aws_ecs_service" "app" {
  name            = "${projectName}-service"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = var.private_subnet_ids
    security_groups  = [var.security_group_id]
    assign_public_ip = false
  }
}

variable "ecs_execution_role_arn" { type = string }
variable "ecs_task_role_arn" { type = string }
variable "container_image" { type = string; default = "nginx:latest" }
variable "region" { type = string }
variable "private_subnet_ids" { type = list(string) }
variable "security_group_id" { type = string }

output "cluster_arn" { value = aws_ecs_cluster.main.arn }
output "service_name" { value = aws_ecs_service.app.name }
output "task_definition_arn" { value = aws_ecs_task_definition.app.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("clusterArn", "${aws_ecs_cluster.main.arn}");
    this.publishOutput("serviceName", "${aws_ecs_service.app.name}");
  }

  protected async configure(): Promise<void> { this.log("ECS service configured"); }
  protected async deploy(): Promise<void> { this.log("ECS deploying new task definition"); }
  protected async validate(): Promise<void> { this.log("ECS service health check"); }
  protected async doRollback(): Promise<void> { this.log("ECS rollback: terraform destroy"); }
}
