import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class ElastiCacheAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc", "vpcId");
    const projectName = this.context.plan.source.split("/").pop() || "launch";

    const tf = `# ElastiCache Configuration — Generated by Launch Platform
resource "aws_elasticache_subnet_group" "main" {
  name       = "${projectName}-cache-subnet"
  subnet_ids = var.private_subnet_ids
}

resource "aws_security_group" "cache" {
  name_prefix = "${projectName}-cache-"
  vpc_id      = var.vpc_id
  ingress {
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [var.app_security_group_id]
  }
}

resource "aws_elasticache_cluster" "main" {
  cluster_id           = "${projectName}-cache"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  subnet_group_name    = aws_elasticache_subnet_group.main.name
  security_group_ids   = [aws_security_group.cache.id]
}

variable "vpc_id" { type = string }
variable "private_subnet_ids" { type = list(string) }
variable "app_security_group_id" { type = string }

output "endpoint" { value = aws_elasticache_cluster.main.cache_nodes[0].address }
output "port" { value = aws_elasticache_cluster.main.cache_nodes[0].port }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("endpoint", "${aws_elasticache_cluster.main.cache_nodes[0].address}");
    this.publishOutput("port", 6379);
  }

  protected async configure(): Promise<void> { this.log("ElastiCache configured"); }
  protected async deploy(): Promise<void> { this.log("ElastiCache ready"); }
  protected async validate(): Promise<void> { this.log("ElastiCache connectivity check"); }
  protected async doRollback(): Promise<void> { this.log("ElastiCache rollback"); }
}
