import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class FirestoreAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";
    const region = this.context.plan.region;

    const tf = `# Firestore — Generated by SASA Launch
resource "google_firestore_database" "main" {
  project     = "${projectId}"
  name        = "(default)"
  location_id = "${region}"
  type        = "FIRESTORE_NATIVE"
}

output "database_name" { value = google_firestore_database.main.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("databaseName", "${google_firestore_database.main.name}");
  }

  protected async configure(): Promise<void> { this.log("Firestore configured"); }
  protected async deploy(): Promise<void> { this.log("Firestore ready"); }
  protected async validate(): Promise<void> { this.log("Firestore accessible"); }
  protected async doRollback(): Promise<void> { this.log("Firestore rollback"); }
}
