import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class GCEAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc-gcp", "publicSubnet");
    const projectName = this.getProjectName();
    const region = this.context.plan.region;
    const zone = `${region}-a`;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Compute Engine VM — Generated by SASA Launch
resource "google_compute_instance" "app" {
  name         = "${projectName}-vm"
  machine_type = "e2-micro"
  zone         = "${zone}"
  project      = "${projectId}"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 20
    }
  }

  network_interface {
    subnetwork = var.subnet_name
    access_config {}
  }

  metadata_startup_script = <<-EOF
    #!/bin/bash
    apt-get update
    apt-get install -y docker.io
    systemctl start docker
    systemctl enable docker
  EOF

  tags = ["web", "${projectName}"]

  service_account {
    email  = var.service_account_email
    scopes = ["cloud-platform"]
  }
}

variable "subnet_name" { type = string }
variable "service_account_email" { type = string; default = "" }

output "instance_name" { value = google_compute_instance.app.name }
output "external_ip" { value = google_compute_instance.app.network_interface[0].access_config[0].nat_ip }
output "internal_ip" { value = google_compute_instance.app.network_interface[0].network_ip }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("instanceName", "${google_compute_instance.app.name}");
    this.publishOutput("externalIp", "${google_compute_instance.app.network_interface[0].access_config[0].nat_ip}");
  }

  protected async configure(): Promise<void> { this.log("GCE instance configured"); }
  protected async deploy(): Promise<void> { this.log("GCE: deploying application"); }
  protected async validate(): Promise<void> { this.log("GCE health check"); }
  protected async doRollback(): Promise<void> { this.log("GCE rollback: terraform destroy"); }
}
