import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class GCSAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Cloud Storage — Generated by SASA Launch
resource "google_storage_bucket" "main" {
  name          = "${projectId}-${projectName}-assets"
  location      = "${region}"
  project       = "${projectId}"
  force_destroy = true

  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  lifecycle_rule {
    condition {
      age = 90
    }
    action {
      type = "Delete"
    }
  }
}

output "bucket_name" { value = google_storage_bucket.main.name }
output "bucket_url" { value = google_storage_bucket.main.url }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("bucketName", "${google_storage_bucket.main.name}");
    this.publishOutput("bucketUrl", "${google_storage_bucket.main.url}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Storage configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud Storage: uploading assets"); }
  protected async validate(): Promise<void> { this.log("Cloud Storage bucket accessible"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Storage rollback"); }
}
