import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class GKEAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc-gcp", "vpcId").catch(() => null);
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const region = this.context.plan.region;
    const cfg = this.context.recommendation.config as {
      autopilot?: boolean;
      releaseChannel?: "RAPID" | "REGULAR" | "STABLE";
    };

    const autopilot = cfg.autopilot ?? true;
    const channel = cfg.releaseChannel ?? "REGULAR";

    const clusterBody = autopilot
      ? `enable_autopilot = true

  ip_allocation_policy {}`
      : `initial_node_count = 1
  remove_default_node_pool = true

  node_config {
    machine_type = "e2-small"
    disk_size_gb = 50
  }

  ip_allocation_policy {}`;

    const tf = `# GKE ${autopilot ? "(Autopilot)" : ""} — Generated by Launch Platform
resource "google_container_cluster" "main" {
  project  = "${projectId}"
  name     = "${projectName}-cluster"
  location = "${region}"

  ${clusterBody}

  release_channel { channel = "${channel}" }

  network    = google_compute_network.main.id
  subnetwork = google_compute_subnetwork.public.id

  # Required for Autopilot/private + sane defaults
  workload_identity_config {
    workload_pool = "${projectId}.svc.id.goog"
  }

  deletion_protection = false
}

output "cluster_name"     { value = google_container_cluster.main.name }
output "cluster_endpoint" { value = google_container_cluster.main.endpoint sensitive = true }
output "cluster_ca_cert"  { value = google_container_cluster.main.master_auth[0].cluster_ca_certificate sensitive = true }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("clusterName", "${google_container_cluster.main.name}");
    this.publishOutput("clusterEndpoint", "${google_container_cluster.main.endpoint}");
  }

  protected async configure(): Promise<void> { this.log("GKE configured"); }
  protected async deploy(): Promise<void>   { this.log("GKE deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("GKE cluster accessible via kubectl"); }
  protected async doRollback(): Promise<void> { this.log("GKE rollback: terraform destroy"); }
}
