import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class LambdaAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("iam", "lambdaExecutionRoleArn");
    const projectName = this.getProjectName();

    const tf = `# Lambda Configuration — Generated by Launch Platform
resource "aws_lambda_function" "app" {
  function_name = "${projectName}-function"
  runtime       = "nodejs20.x"
  handler       = "index.handler"
  role          = var.lambda_execution_role_arn
  memory_size   = 256
  timeout       = 30
  filename      = "lambda.zip"

  environment {
    variables = { NODE_ENV = "production" }
  }
}

resource "aws_lambda_function_url" "app" {
  function_name      = aws_lambda_function.app.function_name
  authorization_type = "NONE"
}

variable "lambda_execution_role_arn" { type = string }

output "function_arn" { value = aws_lambda_function.app.arn }
output "function_url" { value = aws_lambda_function_url.app.function_url }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("functionArn", "${aws_lambda_function.app.arn}");
    this.publishOutput("functionUrl", "${aws_lambda_function_url.app.function_url}");
  }

  protected async configure(): Promise<void> { this.log("Lambda configured"); }
  protected async deploy(): Promise<void> { this.log("Lambda deploying function code"); }
  protected async validate(): Promise<void> { this.log("Lambda function validation"); }
  protected async doRollback(): Promise<void> { this.log("Lambda rollback: terraform destroy"); }
}
