import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class RDSAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc", "vpcId");
    const projectName = this.context.plan.source.split("/").pop() || "launch";
    const engine = (this.context.recommendation.config.engine as string) || "postgres";

    const tf = `# RDS Configuration — Generated by Launch Platform
resource "aws_db_subnet_group" "main" {
  name       = "${projectName}-db-subnet"
  subnet_ids = var.private_subnet_ids
}

resource "aws_security_group" "db" {
  name_prefix = "${projectName}-db-"
  vpc_id      = var.vpc_id

  ingress {
    from_port       = ${engine === "mysql" ? 3306 : 5432}
    to_port         = ${engine === "mysql" ? 3306 : 5432}
    protocol        = "tcp"
    security_groups = [var.app_security_group_id]
  }
}

resource "aws_db_instance" "main" {
  identifier              = "${projectName}-db"
  engine                  = "${engine}"
  engine_version          = "${engine === "mysql" ? "8.0" : "16"}"
  instance_class          = "db.t3.micro"
  allocated_storage       = 20
  db_name                 = "${projectName.replace(/[^a-zA-Z0-9]/g, "")}db"
  username                = "admin"
  manage_master_user_password = true
  db_subnet_group_name    = aws_db_subnet_group.main.name
  vpc_security_group_ids  = [aws_security_group.db.id]
  skip_final_snapshot     = true
  publicly_accessible     = false
}

variable "vpc_id" { type = string }
variable "private_subnet_ids" { type = list(string) }
variable "app_security_group_id" { type = string }

output "endpoint" { value = aws_db_instance.main.endpoint }
output "port" { value = aws_db_instance.main.port }
output "database_name" { value = aws_db_instance.main.db_name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("endpoint", "${aws_db_instance.main.endpoint}");
    this.publishOutput("port", "${aws_db_instance.main.port}");
    this.publishOutput("databaseName", "${aws_db_instance.main.db_name}");
  }

  protected async configure(): Promise<void> { this.log("RDS configured"); }
  protected async deploy(): Promise<void> { this.log("RDS migrations would run here"); }
  protected async validate(): Promise<void> { this.log("RDS connectivity check"); }
  protected async doRollback(): Promise<void> { this.log("RDS rollback: terraform destroy"); }
}
