import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class Route53Agent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      hostedZoneId?: string;
      hostedZoneName?: string;
      subdomain?: string;
      target?: "alb" | "cloudfront";
    };

    // Behavior: if a hosted zone is configured, generate a working alias
    // record. Otherwise, write a stub .tf with a comment block — the merged
    // stack will still validate (no resources, no errors).

    if (!cfg.hostedZoneId && !cfg.hostedZoneName) {
      const stub = `# Route53 — skipped
# No hostedZoneId / hostedZoneName configured for this deployment.
# To enable DNS records, add to the service config:
#   { "hostedZoneId": "Z123...", "subdomain": "app", "target": "alb" }
# or
#   { "hostedZoneName": "example.com", "subdomain": "app", "target": "alb" }
`;
      writeFileSync(join(this.context.artifactDir, "main.tf"), stub);
      this.log("Route53 skipped: no hosted zone configured");
      this.publishOutput("recordFqdn", "not-configured");
      return;
    }

    const subdomain = cfg.subdomain ?? projectName;
    const target = cfg.target ?? "alb";

    // Resolve zone — by id or by name lookup
    const zoneBlock = cfg.hostedZoneId
      ? `data "aws_route53_zone" "main" { zone_id = "${cfg.hostedZoneId}" }`
      : `data "aws_route53_zone" "main" { name = "${cfg.hostedZoneName!}" private_zone = false }`;

    // Wait for the target's outputs so the alias can resolve in the merged stack
    let aliasBlock: string;
    if (target === "cloudfront") {
      await this.waitFor("cloudfront", "domainName");
      aliasBlock = `alias {
    name                   = aws_cloudfront_distribution.main.domain_name
    zone_id                = "Z2FDTNDATAQYW2" # CloudFront's hardcoded hosted zone id
    evaluate_target_health = false
  }`;
    } else {
      await this.waitFor("alb", "albDnsName");
      await this.waitFor("alb", "albZoneId");
      aliasBlock = `alias {
    name                   = aws_lb.main.dns_name
    zone_id                = aws_lb.main.zone_id
    evaluate_target_health = true
  }`;
    }

    const tf = `# Route53 — Generated by Launch Platform
${zoneBlock}

resource "aws_route53_record" "app" {
  zone_id = data.aws_route53_zone.main.zone_id
  name    = "${subdomain}.\${data.aws_route53_zone.main.name}"
  type    = "A"

  ${aliasBlock}
}

output "record_fqdn" { value = aws_route53_record.app.fqdn }
output "zone_id"     { value = data.aws_route53_zone.main.zone_id }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.log(`Route53 record will be created: ${subdomain} → ${target}`);
    this.publishOutput("recordFqdn", "${aws_route53_record.app.fqdn}");
    this.publishOutput("zoneId", "${data.aws_route53_zone.main.zone_id}");
  }

  protected async configure(): Promise<void> { this.log("Route53 configured"); }
  protected async deploy(): Promise<void> { this.log("Route53 DNS via terraform"); }
  protected async validate(): Promise<void> { this.log("Route53 validation: skipped (DNS propagation)"); }
  protected async doRollback(): Promise<void> { this.log("Route53 rollback: terraform destroy"); }
}
