import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class Route53Agent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.context.plan.source.split("/").pop() || "launch";

    const tf = `# Route53 Configuration — Generated by Launch Platform
# NOTE: Requires an existing hosted zone. Update the zone_id variable.

# resource "aws_route53_record" "app" {
#   zone_id = var.hosted_zone_id
#   name    = "${projectName}"
#   type    = "A"
#   alias {
#     name                   = var.alb_dns_name
#     zone_id                = var.alb_zone_id
#     evaluate_target_health = true
#   }
# }

# variable "hosted_zone_id" { type = string }
# variable "alb_dns_name" { type = string }
# variable "alb_zone_id" { type = string }

# output "domain_name" { value = aws_route53_record.app.fqdn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.log("Route53 template generated (commented — requires hosted zone)");
    this.publishOutput("domainName", "pending-dns-configuration");
  }

  protected async configure(): Promise<void> { this.log("Route53 configuration requires manual DNS setup"); }
  protected async deploy(): Promise<void> { this.log("Route53 DNS records"); }
  protected async validate(): Promise<void> { this.log("Route53 validation skipped (manual setup)"); }
  protected async doRollback(): Promise<void> { this.log("Route53 rollback"); }
}
