import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class S3Agent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();

    const tf = `# S3 Configuration — Generated by Launch Platform
resource "aws_s3_bucket" "main" {
  bucket_prefix = "${projectName}-"
}

resource "aws_s3_bucket_versioning" "main" {
  bucket = aws_s3_bucket.main.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "main" {
  bucket = aws_s3_bucket.main.id
  rule {
    apply_server_side_encryption_by_default { sse_algorithm = "AES256" }
  }
}

resource "aws_s3_bucket_public_access_block" "main" {
  bucket                  = aws_s3_bucket.main.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

output "bucket_name" { value = aws_s3_bucket.main.id }
output "bucket_arn" { value = aws_s3_bucket.main.arn }
output "bucket_domain" { value = aws_s3_bucket.main.bucket_regional_domain_name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("bucketName", "${aws_s3_bucket.main.id}");
    this.publishOutput("bucketArn", "${aws_s3_bucket.main.arn}");
  }

  protected async configure(): Promise<void> { this.log("S3 configured"); }
  protected async deploy(): Promise<void> { this.log("S3 asset upload"); }
  protected async validate(): Promise<void> { this.log("S3 bucket accessible"); }
  protected async doRollback(): Promise<void> { this.log("S3 rollback: terraform destroy"); }
}
