import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class SecretManagerGCPAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.context.plan.source.split("/").pop()?.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase() || "launch";
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Secret Manager — Generated by SASA Launch
resource "google_secret_manager_secret" "app_secrets" {
  for_each  = toset(var.secret_names)
  secret_id = "${projectName}-\${each.key}"
  project   = "${projectId}"

  replication {
    auto {}
  }
}

variable "secret_names" {
  type    = list(string)
  default = ["database-url", "api-key", "jwt-secret"]
}

output "secret_ids" {
  value = { for k, v in google_secret_manager_secret.app_secrets : k => v.secret_id }
}
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("secretPrefix", `${projectName}`);
  }

  protected async configure(): Promise<void> { this.log("Secret Manager configured"); }
  protected async deploy(): Promise<void> { this.log("Secret Manager: populate secrets"); }
  protected async validate(): Promise<void> { this.log("Secret Manager accessible"); }
  protected async doRollback(): Promise<void> { this.log("Secret Manager rollback"); }
}
