import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class SQSAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();

    const tf = `# SQS Configuration — Generated by Launch Platform
resource "aws_sqs_queue" "main" {
  name                       = "${projectName}-queue"
  delay_seconds              = 0
  max_message_size           = 262144
  message_retention_seconds  = 345600
  receive_wait_time_seconds  = 10
  visibility_timeout_seconds = 60
}

resource "aws_sqs_queue" "dlq" {
  name = "${projectName}-queue-dlq"
}

resource "aws_sqs_queue_redrive_policy" "main" {
  queue_url = aws_sqs_queue.main.id
  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dlq.arn
    maxReceiveCount     = 3
  })
}

output "queue_url" { value = aws_sqs_queue.main.url }
output "queue_arn" { value = aws_sqs_queue.main.arn }
output "dlq_url" { value = aws_sqs_queue.dlq.url }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("queueUrl", "${aws_sqs_queue.main.url}");
    this.publishOutput("queueArn", "${aws_sqs_queue.main.arn}");
  }

  protected async configure(): Promise<void> { this.log("SQS configured"); }
  protected async deploy(): Promise<void> { this.log("SQS ready"); }
  protected async validate(): Promise<void> { this.log("SQS queue accessible"); }
  protected async doRollback(): Promise<void> { this.log("SQS rollback"); }
}
