import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class VPCAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const region = this.context.plan.region;
    const projectName = this.context.plan.source.split("/").pop() || "launch";

    const tf = `# VPC Configuration — Generated by Launch Platform
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = { Name = "${projectName}-vpc" }
}

resource "aws_subnet" "public_1" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.1.0/24"
  availability_zone       = "${region}a"
  map_public_ip_on_launch = true
  tags = { Name = "${projectName}-public-1" }
}

resource "aws_subnet" "public_2" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.2.0/24"
  availability_zone       = "${region}b"
  map_public_ip_on_launch = true
  tags = { Name = "${projectName}-public-2" }
}

resource "aws_subnet" "private_1" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.10.0/24"
  availability_zone = "${region}a"
  tags = { Name = "${projectName}-private-1" }
}

resource "aws_subnet" "private_2" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.11.0/24"
  availability_zone = "${region}b"
  tags = { Name = "${projectName}-private-2" }
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
  tags   = { Name = "${projectName}-igw" }
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
  tags = { Name = "${projectName}-public-rt" }
}

resource "aws_route_table_association" "public_1" {
  subnet_id      = aws_subnet.public_1.id
  route_table_id = aws_route_table.public.id
}

resource "aws_route_table_association" "public_2" {
  subnet_id      = aws_subnet.public_2.id
  route_table_id = aws_route_table.public.id
}

resource "aws_security_group" "app" {
  name_prefix = "${projectName}-app-"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = { Name = "${projectName}-app-sg" }
}

output "vpc_id" { value = aws_vpc.main.id }
output "public_subnet_ids" { value = [aws_subnet.public_1.id, aws_subnet.public_2.id] }
output "private_subnet_ids" { value = [aws_subnet.private_1.id, aws_subnet.private_2.id] }
output "security_group_id" { value = aws_security_group.app.id }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.log("Generated VPC Terraform configuration");

    this.publishOutput("vpcId", "${aws_vpc.main.id}");
    this.publishOutput("publicSubnetIds", ["${aws_subnet.public_1.id}", "${aws_subnet.public_2.id}"]);
    this.publishOutput("privateSubnetIds", ["${aws_subnet.private_1.id}", "${aws_subnet.private_2.id}"]);
    this.publishOutput("securityGroupId", "${aws_security_group.app.id}");
  }

  protected async configure(): Promise<void> {
    this.log("VPC configuration complete (no additional config needed)");
  }

  protected async deploy(): Promise<void> {
    this.log("VPC deployment handled by Terraform apply");
  }

  protected async validate(): Promise<void> {
    this.log("VPC validation: Terraform plan verified resource creation");
  }

  protected async doRollback(): Promise<void> {
    this.log("VPC rollback: terraform destroy would remove VPC resources");
  }
}
