#!/usr/bin/env node
// Cross-platform GCP Secret Manager CLI for local dev.
//
// Usage:
//   PROJECT_ID=<id> npm run secrets:pull          # download → .env.local
//   PROJECT_ID=<id> npm run secrets:push          # upload from .env (or ENV_FILE)
//   PROJECT_ID=<id> npm run secrets:list          # list managed secrets in GCP
//
// Auth: run `gcloud auth application-default login` once.

import { SecretManagerServiceClient } from "@google-cloud/secret-manager";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { MANAGED } from "./secrets.config.mjs";

const PROJECT_ID = process.env.PROJECT_ID;
const RUNTIME_SA = process.env.RUNTIME_SA || "sasa-runtime";

if (!PROJECT_ID) {
  console.error("error: PROJECT_ID env var is required");
  process.exit(1);
}

const cmd = process.argv[2];
const client = new SecretManagerServiceClient();
const parent = `projects/${PROJECT_ID}`;
const runtimeMember = `serviceAccount:${RUNTIME_SA}@${PROJECT_ID}.iam.gserviceaccount.com`;

async function main() {
  switch (cmd) {
    case "pull": return pull();
    case "push": return push();
    case "list": return list();
    default:
      console.error("usage: secrets.mjs <pull|push|list>");
      process.exit(2);
  }
}

function parseEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1);
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

async function secretExists(name) {
  try {
    await client.getSecret({ name: `${parent}/secrets/${name}` });
    return true;
  } catch (e) {
    if (e.code === 5) return false; // NOT_FOUND
    throw e;
  }
}

async function upsert(name, value) {
  const exists = await secretExists(name);
  if (!exists) {
    await client.createSecret({
      parent,
      secretId: name,
      secret: { replication: { automatic: {} } },
    });
  }
  await client.addSecretVersion({
    parent: `${parent}/secrets/${name}`,
    payload: { data: Buffer.from(value, "utf8") },
  });
  // Grant runtime SA access (idempotent).
  const resource = `${parent}/secrets/${name}`;
  const [policy] = await client.getIamPolicy({ resource });
  const role = "roles/secretmanager.secretAccessor";
  const binding = policy.bindings?.find((b) => b.role === role);
  if (binding) {
    if (!binding.members.includes(runtimeMember)) binding.members.push(runtimeMember);
  } else {
    policy.bindings = [...(policy.bindings || []), { role, members: [runtimeMember] }];
  }
  await client.setIamPolicy({ resource, policy });
  return exists ? "updated" : "created";
}

async function push() {
  const file = process.env.ENV_FILE || "./.env";
  if (!fs.existsSync(file)) {
    console.error(`error: ${file} not found`);
    process.exit(1);
  }
  const env = parseEnvFile(file);
  for (const name of MANAGED) {
    const val = env[name];
    if (val === undefined || val === "") {
      console.log(`  -  ${name} (skipped, not in ${file})`);
      continue;
    }
    const status = await upsert(name, val);
    console.log(`  +  ${name} (${status})`);
  }
  console.log("done.");
}

async function pull() {
  const out = process.env.OUT_FILE || "./.env.local";
  const merge = process.env.MERGE === "1";

  let preserved = "";
  if (merge && fs.existsSync(out)) {
    const existing = parseEnvFile(out);
    preserved = Object.entries(existing)
      .filter(([k]) => !MANAGED.includes(k))
      .map(([k, v]) => `${k}=${v}`)
      .join("\n");
    if (preserved) preserved += "\n\n";
  }

  const lines = [
    `# Generated by npm run secrets:pull — do not edit by hand.`,
    `# Source: GCP Secret Manager, project=${PROJECT_ID}`,
    "",
  ];
  const written = [];
  const skipped = [];
  for (const name of MANAGED) {
    try {
      const [resp] = await client.accessSecretVersion({
        name: `${parent}/secrets/${name}/versions/latest`,
      });
      const value = resp.payload?.data?.toString("utf8") ?? "";
      lines.push(`${name}=${value}`);
      written.push(name);
    } catch (e) {
      if (e.code === 5 || e.code === 7) skipped.push(name);
      else throw e;
    }
  }

  const tmp = path.join(os.tmpdir(), `env.${Date.now()}.${process.pid}`);
  fs.writeFileSync(tmp, preserved + lines.join("\n") + "\n", { mode: 0o600 });
  fs.renameSync(tmp, out);
  try { fs.chmodSync(out, 0o600); } catch {} // best effort on Windows

  console.log(`wrote ${out}`);
  for (const k of written) console.log(`  + ${k}`);
  if (skipped.length) {
    console.log("skipped (not in Secret Manager or no access):");
    for (const k of skipped) console.log(`  - ${k}`);
  }
}

async function list() {
  const [secrets] = await client.listSecrets({ parent });
  const present = new Set(secrets.map((s) => s.name.split("/").pop()));
  for (const name of MANAGED) {
    console.log(`  ${present.has(name) ? "✓" : "·"} ${name}`);
  }
  const extras = [...present].filter((n) => !MANAGED.includes(n));
  if (extras.length) {
    console.log("\nIn project but not in MANAGED whitelist:");
    for (const n of extras) console.log(`  ? ${n}`);
  }
}

main().catch((e) => {
  if (e.code === 16 || /could not load the default credentials/i.test(e.message || "")) {
    console.error("error: no GCP credentials. Run: gcloud auth application-default login");
    process.exit(1);
  }
  console.error(e.message || e);
  process.exit(1);
});
