#!/usr/bin/env node
// Cross-platform GCP Secret Manager CLI for local dev.
//
// Usage:
//   PROJECT_ID=<id> npm run secrets:pull          # download → .env.local
//   PROJECT_ID=<id> npm run secrets:push          # upload from .env (or ENV_FILE)
//   PROJECT_ID=<id> npm run secrets:list          # list managed secrets in GCP
//
// Auth: run `gcloud auth application-default login` once.

import { SecretManagerServiceClient } from "@google-cloud/secret-manager";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { MANAGED } from "./secrets.config.mjs";

// gRPC status codes we branch on (https://grpc.github.io/grpc/core/md_doc_statuscodes.html).
const GRPC = {
  NOT_FOUND: 5,
  ALREADY_EXISTS: 6,
  PERMISSION_DENIED: 7,
  UNAUTHENTICATED: 16,
};

const PROJECT_ID = process.env.PROJECT_ID;
const RUNTIME_SA = process.env.RUNTIME_SA || "sasa-runtime";

if (!PROJECT_ID) {
  console.error("error: PROJECT_ID env var is required");
  process.exit(1);
}

const cmd = process.argv[2];
const client = new SecretManagerServiceClient();
const parent = `projects/${PROJECT_ID}`;
const runtimeMember = `serviceAccount:${RUNTIME_SA}@${PROJECT_ID}.iam.gserviceaccount.com`;

async function main() {
  switch (cmd) {
    case "pull": return pull();
    case "push": return push();
    case "list": return list();
    default:
      console.error("usage: secrets.mjs <pull|push|list>");
      process.exit(2);
  }
}

function parseEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1);
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

async function upsert(name, value) {
  // Try-create-catch-ALREADY_EXISTS — one round-trip vs. the get-then-create
  // TOCTOU pattern. AlreadyExists is the explicit "secret already there" signal.
  let created = false;
  try {
    await client.createSecret({
      parent,
      secretId: name,
      secret: { replication: { automatic: {} } },
    });
    created = true;
  } catch (e) {
    if (e.code !== GRPC.ALREADY_EXISTS) throw e;
  }

  const resource = `${parent}/secrets/${name}`;
  const role = "roles/secretmanager.secretAccessor";

  // Add the version and reconcile IAM in parallel — independent ops on the same secret.
  await Promise.all([
    client.addSecretVersion({ parent: resource, payload: { data: Buffer.from(value, "utf8") } }),
    (async () => {
      const [policy] = await client.getIamPolicy({ resource });
      const binding = policy.bindings?.find((b) => b.role === role);
      if (binding) {
        if (!binding.members.includes(runtimeMember)) binding.members.push(runtimeMember);
        else return; // already bound — skip the no-op setIamPolicy
      } else {
        policy.bindings = [...(policy.bindings || []), { role, members: [runtimeMember] }];
      }
      await client.setIamPolicy({ resource, policy });
    })(),
  ]);

  return created ? "created" : "updated";
}

async function push() {
  const file = process.env.ENV_FILE || "./.env";
  if (!fs.existsSync(file)) {
    console.error(`error: ${file} not found`);
    process.exit(1);
  }
  const env = parseEnvFile(file);
  const results = await Promise.all(
    MANAGED.map(async (name) => {
      const val = env[name];
      if (val === undefined || val === "") return { name, status: "skipped" };
      const status = await upsert(name, val);
      return { name, status };
    }),
  );
  for (const { name, status } of results) {
    const sign = status === "skipped" ? "-" : "+";
    const note = status === "skipped" ? `skipped, not in ${file}` : status;
    console.log(`  ${sign}  ${name} (${note})`);
  }
  console.log("done.");
}

async function pull() {
  const out = process.env.OUT_FILE || "./.env.local";
  const merge = process.env.MERGE === "1";

  let preserved = "";
  if (merge && fs.existsSync(out)) {
    const existing = parseEnvFile(out);
    preserved = Object.entries(existing)
      .filter(([k]) => !MANAGED.includes(k))
      .map(([k, v]) => `${k}=${v}`)
      .join("\n");
    if (preserved) preserved += "\n\n";
  }

  const lines = [
    `# Generated by npm run secrets:pull`,
    `# Source: GCP Secret Manager, project=${PROJECT_ID}`,
    "",
  ];
  // Fetch all secrets in parallel — each is an independent network round-trip.
  const fetched = await Promise.all(
    MANAGED.map(async (name) => {
      try {
        const [resp] = await client.accessSecretVersion({
          name: `${parent}/secrets/${name}/versions/latest`,
        });
        return { name, value: resp.payload?.data?.toString("utf8") ?? "", ok: true };
      } catch (e) {
        if (e.code === GRPC.NOT_FOUND || e.code === GRPC.PERMISSION_DENIED) {
          return { name, ok: false };
        }
        throw e;
      }
    }),
  );
  const written = [];
  const skipped = [];
  for (const r of fetched) {
    if (r.ok) {
      lines.push(`${r.name}=${r.value}`);
      written.push(r.name);
    } else {
      skipped.push(r.name);
    }
  }

  const tmp = path.join(os.tmpdir(), `env.${Date.now()}.${process.pid}`);
  fs.writeFileSync(tmp, preserved + lines.join("\n") + "\n", { mode: 0o600 });
  fs.renameSync(tmp, out);
  try { fs.chmodSync(out, 0o600); } catch {} // best effort on Windows

  console.log(`wrote ${out}`);
  for (const k of written) console.log(`  + ${k}`);
  if (skipped.length) {
    console.log("skipped (not in Secret Manager or no access):");
    for (const k of skipped) console.log(`  - ${k}`);
  }
}

async function list() {
  const [secrets] = await client.listSecrets({ parent });
  const present = new Set(secrets.map((s) => s.name.split("/").pop()));
  for (const name of MANAGED) {
    console.log(`  ${present.has(name) ? "✓" : "·"} ${name}`);
  }
  const extras = [...present].filter((n) => !MANAGED.includes(n));
  if (extras.length) {
    console.log("\nIn project but not in MANAGED whitelist:");
    for (const n of extras) console.log(`  ? ${n}`);
  }
}

main().catch((e) => {
  if (e.code === GRPC.UNAUTHENTICATED || /could not load the default credentials/i.test(e.message || "")) {
    console.error("error: no GCP credentials. Run: gcloud auth application-default login");
    process.exit(1);
  }
  console.error(e.message || e);
  process.exit(1);
});
