import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class ALBAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc", "vpcId");
    const projectName = this.getProjectName();

    const tf = `# ALB Configuration — Generated by Launch Platform
resource "aws_lb" "main" {
  name               = "${projectName}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [var.security_group_id]
  subnets            = var.public_subnet_ids
}

resource "aws_lb_target_group" "app" {
  name        = "${projectName}-tg"
  port        = 3000
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    path                = "/health"
    healthy_threshold   = 2
    unhealthy_threshold = 3
    timeout             = 5
    interval            = 30
  }
}

resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.main.arn
  port              = 80
  protocol          = "HTTP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }
}

variable "vpc_id" { type = string }
variable "public_subnet_ids" { type = list(string) }
variable "security_group_id" { type = string }

output "alb_arn" { value = aws_lb.main.arn }
output "alb_dns_name" { value = aws_lb.main.dns_name }
output "alb_zone_id" { value = aws_lb.main.zone_id }
output "target_group_arn" { value = aws_lb_target_group.app.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("albArn", "${aws_lb.main.arn}");
    this.publishOutput("albDnsName", "${aws_lb.main.dns_name}");
    this.publishOutput("albZoneId", "${aws_lb.main.zone_id}");
    this.publishOutput("targetGroupArn", "${aws_lb_target_group.app.arn}");
  }

  protected async configure(): Promise<void> { this.log("ALB configured"); }
  protected async deploy(): Promise<void> { this.log("ALB routing active"); }
  protected async validate(): Promise<void> { this.log("ALB health check passing"); }
  protected async doRollback(): Promise<void> { this.log("ALB rollback"); }
}
