import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class AppRunnerAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      imageUri?: string;        // e.g. "public.ecr.aws/.../foo:latest"
      port?: string;            // string per AWS schema
      cpu?: string;             // "1024" = 1 vCPU
      memory?: string;          // "2048"
      autoDeployments?: boolean;
      env?: Record<string, string>;
    };

    const port = cfg.port ?? "3000";
    const cpu = cfg.cpu ?? "1024";
    const memory = cfg.memory ?? "2048";
    const autoDeploy = cfg.autoDeployments ?? true;

    // If ECR is in the deployment, default the image to "<repo-url>:latest"
    const usesEcr = this.dependencies.includes("ecr");
    if (usesEcr) {
      await this.waitFor("ecr", "repositoryUrl").catch(() => null);
    }

    const imageUri = cfg.imageUri
      ?? (usesEcr ? "${aws_ecr_repository.main.repository_url}:latest" : "public.ecr.aws/aws-containers/hello-app-runner:latest");

    const envBlock = cfg.env && Object.keys(cfg.env).length
      ? `runtime_environment_variables = {
${Object.entries(cfg.env).map(([k, v]) => `          ${JSON.stringify(k)} = ${JSON.stringify(v)}`).join("\n")}
        }`
      : "";

    const tf = `# App Runner — Generated by Launch Platform
resource "aws_iam_role" "apprunner_access" {
  name = "${projectName}-apprunner-access"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "build.apprunner.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "apprunner_ecr" {
  role       = aws_iam_role.apprunner_access.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess"
}

resource "aws_apprunner_service" "main" {
  service_name = "${projectName}-app"

  source_configuration {
    auto_deployments_enabled = ${autoDeploy}

    authentication_configuration {
      access_role_arn = aws_iam_role.apprunner_access.arn
    }

    image_repository {
      image_identifier      = "${imageUri}"
      image_repository_type = "ECR"
      image_configuration {
        port = "${port}"
        ${envBlock}
      }
    }
  }

  instance_configuration {
    cpu    = "${cpu}"
    memory = "${memory}"
  }

  health_check_configuration {
    protocol            = "HTTP"
    path                = "/health"
    interval            = 10
    timeout             = 5
    healthy_threshold   = 1
    unhealthy_threshold = 3
  }

  tags = { Name = "${projectName}-apprunner" }
}

output "service_url" { value = aws_apprunner_service.main.service_url }
output "service_arn" { value = aws_apprunner_service.main.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("serviceUrl", "${aws_apprunner_service.main.service_url}");
    this.publishOutput("serviceArn", "${aws_apprunner_service.main.arn}");
  }

  protected async configure(): Promise<void> { this.log("App Runner configured"); }
  protected async deploy(): Promise<void>   { this.log("App Runner deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("App Runner service running"); }
  protected async doRollback(): Promise<void> { this.log("App Runner rollback"); }

  async stop() {
    this.log("App Runner stop: use 'aws apprunner pause-service' (terraform doesn't model paused state)");
    return { success: false, outputs: {}, error: "stop() requires aws apprunner pause-service CLI call" };
  }
}
