import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

/**
 * AWS Bedrock agent. Bedrock itself doesn't require provisioning of an
 * "instance" — model access is API-driven. What we DO provision:
 *   - An IAM role + policy that grants the user's compute (Lambda, ECS,
 *     EKS) `bedrock:InvokeModel` on a pinned set of foundation models.
 *   - A Bedrock guardrail with a sane default content filter (toggle off
 *     via config.skipGuardrail).
 *   - Optional: a Bedrock Knowledge Base wired to an S3 data source
 *     (toggle via config.knowledgeBase = true).
 *
 * Model access in Bedrock must also be granted manually in the AWS
 * console (one-time per region). The agent logs a reminder.
 */
export class BedrockAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      modelIds?: string[];
      skipGuardrail?: boolean;
      knowledgeBase?: boolean;
      knowledgeBaseS3Bucket?: string;
    };
    const modelIds = cfg.modelIds ?? [
      "anthropic.claude-3-5-sonnet-20241022-v2:0",
      "anthropic.claude-3-haiku-20240307-v1:0",
    ];
    const guardrail = !cfg.skipGuardrail;
    const kb = !!cfg.knowledgeBase;

    const modelArns = modelIds
      .map((m) => `"arn:aws:bedrock:*::foundation-model/${m}"`)
      .join(",\n      ");

    const guardrailBlock = guardrail
      ? `
resource "aws_bedrock_guardrail" "default" {
  name                      = "${projectName}-guardrail"
  blocked_input_messaging   = "Sorry, that request was blocked by the input guardrail."
  blocked_outputs_messaging = "Sorry, that response was blocked by the output guardrail."

  content_policy_config {
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "HATE"
    }
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "VIOLENCE"
    }
    filters_config {
      input_strength  = "HIGH"
      output_strength = "HIGH"
      type            = "SEXUAL"
    }
  }
}

output "guardrail_id" { value = aws_bedrock_guardrail.default.guardrail_id }
`
      : "";

    const kbBlock =
      kb && cfg.knowledgeBaseS3Bucket
        ? `
resource "aws_bedrockagent_knowledge_base" "default" {
  name     = "${projectName}-kb"
  role_arn = aws_iam_role.bedrock_invoke.arn

  knowledge_base_configuration {
    type = "VECTOR"
    vector_knowledge_base_configuration {
      embedding_model_arn = "arn:aws:bedrock:\${data.aws_region.current.name}::foundation-model/amazon.titan-embed-text-v2:0"
    }
  }

  storage_configuration {
    type = "OPENSEARCH_SERVERLESS"
    # NOTE: opensearch-serverless collection wiring is left to a follow-up
    # — the simplest knowledge base requires more pieces than fit a single
    # agent (collection + access policies + data source).
    opensearch_serverless_configuration {
      collection_arn    = "arn:aws:aoss:::collection/REPLACE_ME"
      vector_index_name = "${projectName}-kb-index"
      field_mapping {
        vector_field   = "vector"
        text_field     = "text"
        metadata_field = "metadata"
      }
    }
  }
}
`
        : "";

    const tf = `# Bedrock IAM + Guardrail — Generated by Launch Platform
data "aws_region" "current" {}

data "aws_iam_policy_document" "bedrock_invoke_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com", "ecs-tasks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "bedrock_invoke" {
  name               = "${projectName}-bedrock-invoke"
  assume_role_policy = data.aws_iam_policy_document.bedrock_invoke_assume.json
}

data "aws_iam_policy_document" "bedrock_invoke_policy" {
  statement {
    actions = ["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"]
    resources = [
      ${modelArns}
    ]
  }
  statement {
    actions   = ["bedrock:GetFoundationModel", "bedrock:ListFoundationModels"]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "bedrock_invoke" {
  role   = aws_iam_role.bedrock_invoke.id
  policy = data.aws_iam_policy_document.bedrock_invoke_policy.json
}
${guardrailBlock}${kbBlock}
output "bedrock_invoke_role_arn" { value = aws_iam_role.bedrock_invoke.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("invokeRoleArn", "${aws_iam_role.bedrock_invoke.arn}");
    this.publishOutput("modelIds", modelIds);
    this.log(
      "REMINDER: Foundation-model access must be granted in the AWS console " +
        "(Bedrock → Model access). One-time per region.",
    );
  }

  protected async configure(): Promise<void> { this.log("Bedrock configured"); }
  protected async deploy(): Promise<void> { this.log("Bedrock deploys via terraform apply"); }
  protected async validate(): Promise<void> { this.log("Bedrock validation: bedrock:ListFoundationModels would go here"); }
  protected async doRollback(): Promise<void> { this.log("Bedrock rollback: terraform destroy"); }
}
