import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudWatchAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const region = this.context.plan.region;

    const tf = `# CloudWatch — Generated by SASA Launch
resource "aws_cloudwatch_log_group" "app" {
  name              = "/app/${projectName}"
  retention_in_days = 30
}

resource "aws_cloudwatch_metric_alarm" "high_cpu" {
  alarm_name          = "${projectName}-high-cpu"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS"
  period              = 300
  statistic           = "Average"
  threshold           = 80
  alarm_description   = "CPU utilization above 80%"
  dimensions = {
    ClusterName = "${projectName}-cluster"
  }
}

resource "aws_cloudwatch_metric_alarm" "high_memory" {
  alarm_name          = "${projectName}-high-memory"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "MemoryUtilization"
  namespace           = "AWS/ECS"
  period              = 300
  statistic           = "Average"
  threshold           = 85
  alarm_description   = "Memory utilization above 85%"
  dimensions = {
    ClusterName = "${projectName}-cluster"
  }
}

resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = "${projectName}-dashboard"
  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6
        properties = {
          metrics = [["AWS/ECS", "CPUUtilization", "ClusterName", "${projectName}-cluster"]]
          period  = 300
          stat    = "Average"
          region  = "${region}"
          title   = "ECS CPU"
        }
      }
    ]
  })
}

output "log_group_name" { value = aws_cloudwatch_log_group.app.name }
output "dashboard_name" { value = aws_cloudwatch_dashboard.main.dashboard_name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("logGroupName", "$\{aws_cloudwatch_log_group.app.name}");
    this.publishOutput("dashboardName", "$\{aws_cloudwatch_dashboard.main.dashboard_name}");
  }

  protected async configure(): Promise<void> { this.log("CloudWatch configured"); }
  protected async deploy(): Promise<void> { this.log("CloudWatch monitoring active"); }
  protected async validate(): Promise<void> { this.log("CloudWatch alarms verified"); }
  protected async doRollback(): Promise<void> { this.log("CloudWatch rollback"); }
}
