import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudRunAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("cloud-iam", "cloudRunServiceAccountEmail");
    const projectName = this.getProjectName();
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Cloud Run Service — Generated by SASA Launch
resource "google_cloud_run_v2_service" "app" {
  name     = "${projectName}-app"
  location = "${region}"
  project  = "${projectId}"

  template {
    scaling {
      min_instance_count = 0
      max_instance_count = 10
    }

    containers {
      image = var.container_image

      ports {
        container_port = 3000
      }

      resources {
        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
      }

      env {
        name  = "NODE_ENV"
        value = "production"
      }
    }

    service_account = var.service_account_email

    vpc_access {
      connector = var.vpc_connector_id
      egress    = "PRIVATE_RANGES_ONLY"
    }
  }

  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }
}

resource "google_cloud_run_service_iam_member" "public_access" {
  location = google_cloud_run_v2_service.app.location
  project  = "${projectId}"
  service  = google_cloud_run_v2_service.app.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}

variable "container_image" {
  type    = string
  default = "gcr.io/cloudrun/hello"
}

variable "service_account_email" { type = string }
variable "vpc_connector_id" {
  type    = string
  default = ""
}

output "service_url" { value = google_cloud_run_v2_service.app.uri }
output "service_name" { value = google_cloud_run_v2_service.app.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("serviceUrl", "${google_cloud_run_v2_service.app.uri}");
    this.publishOutput("serviceName", "${google_cloud_run_v2_service.app.name}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Run service configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud Run deploying new revision"); }
  protected async validate(): Promise<void> { this.log("Cloud Run health check"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Run rollback: terraform destroy"); }
}
