import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudFrontAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();

    // Wait for S3 if it's an upstream dependency. The orchestrator's
    // dependency tier guarantees S3 has provisioned (and published its
    // outputs) before CloudFront starts.
    const hasS3 = this.dependencies.includes("s3");
    if (hasS3) {
      await this.waitFor("s3", "bucketName");
    }

    // Origin config: prefer S3 (private, OAI-protected) when an S3 service
    // is in the same stack. Else fall back to a custom origin domain via
    // recommendation.config.originDomain.
    const cfg = this.context.recommendation.config as { originDomain?: string };

    const originBlock = hasS3
      ? `origin {
    domain_name              = aws_s3_bucket.main.bucket_regional_domain_name
    origin_id                = "${projectName}-s3-origin"
    origin_access_control_id = aws_cloudfront_origin_access_control.main.id
  }`
      : `origin {
    domain_name = "${cfg.originDomain ?? "example.com"}"
    origin_id   = "${projectName}-origin"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }`;

    const oacBlock = hasS3
      ? `resource "aws_cloudfront_origin_access_control" "main" {
  name                              = "${projectName}-oac"
  description                       = "OAC for ${projectName}"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_s3_bucket_policy" "cloudfront_access" {
  bucket = aws_s3_bucket.main.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowCloudFrontServicePrincipalReadOnly"
      Effect    = "Allow"
      Principal = { Service = "cloudfront.amazonaws.com" }
      Action    = "s3:GetObject"
      Resource  = "\${aws_s3_bucket.main.arn}/*"
      Condition = {
        StringEquals = {
          "AWS:SourceArn" = aws_cloudfront_distribution.main.arn
        }
      }
    }]
  })
}

`
      : "";

    const targetOriginId = hasS3 ? `${projectName}-s3-origin` : `${projectName}-origin`;

    const tf = `# CloudFront Configuration — Generated by Launch Platform
${oacBlock}resource "aws_cloudfront_distribution" "main" {
  enabled             = true
  default_root_object = "index.html"
  price_class         = "PriceClass_100"
  is_ipv6_enabled     = true

  ${originBlock}

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "${targetOriginId}"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    # AWS-managed cache policy: CachingOptimized
    cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
    # AWS-managed origin request policy: CORS-S3Origin
    origin_request_policy_id = "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf"
  }

  restrictions {
    geo_restriction { restriction_type = "none" }
  }

  viewer_certificate { cloudfront_default_certificate = true }

  tags = { Name = "${projectName}-cdn" }
}

output "distribution_id" { value = aws_cloudfront_distribution.main.id }
output "domain_name"     { value = aws_cloudfront_distribution.main.domain_name }
output "distribution_arn" { value = aws_cloudfront_distribution.main.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("distributionId", "${aws_cloudfront_distribution.main.id}");
    this.publishOutput("domainName", "${aws_cloudfront_distribution.main.domain_name}");
    this.publishOutput("distributionArn", "${aws_cloudfront_distribution.main.arn}");
  }

  protected async configure(): Promise<void> { this.log("CloudFront configured"); }
  protected async deploy(): Promise<void>   { this.log("CloudFront deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("CloudFront distribution active"); }
  protected async doRollback(): Promise<void> { this.log("CloudFront rollback"); }
}
