import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class CloudSQLAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc-gcp", "networkName");
    const projectName = this.getProjectName();
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";
    const engine = (this.context.recommendation.config.engine as string) || "postgres";
    const dbVersion = engine === "mysql" ? "MYSQL_8_0" : "POSTGRES_16";

    const tf = `# Cloud SQL — Generated by SASA Launch
resource "google_sql_database_instance" "main" {
  name             = "${projectName}-db"
  database_version = "${dbVersion}"
  region           = "${region}"
  project          = "${projectId}"

  settings {
    tier = "db-f1-micro"

    ip_configuration {
      ipv4_enabled    = false
      private_network = var.network_id
    }

    backup_configuration {
      enabled            = true
      start_time         = "03:00"
      binary_log_enabled = ${engine === "mysql" ? "true" : "false"}
    }

    database_flags {
      name  = "${engine === "mysql" ? "max_connections" : "max_connections"}"
      value = "100"
    }
  }

  deletion_protection = false
}

resource "google_sql_database" "app" {
  name     = "${projectName.replace(/[^a-z0-9]/g, "")}db"
  instance = google_sql_database_instance.main.name
  project  = "${projectId}"
}

resource "google_sql_user" "app" {
  name     = "app"
  instance = google_sql_database_instance.main.name
  password = random_password.db_password.result
  project  = "${projectId}"
}

resource "random_password" "db_password" {
  length  = 24
  special = true
}

resource "google_secret_manager_secret" "db_password" {
  secret_id = "${projectName}-db-password"
  project   = "${projectId}"
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db_password.result
}

variable "network_id" { type = string }

output "connection_name" { value = google_sql_database_instance.main.connection_name }
output "private_ip" { value = google_sql_database_instance.main.private_ip_address }
output "database_name" { value = google_sql_database.app.name }
output "db_secret_id" { value = google_secret_manager_secret.db_password.secret_id }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("connectionName", "${google_sql_database_instance.main.connection_name}");
    this.publishOutput("privateIp", "${google_sql_database_instance.main.private_ip_address}");
    this.publishOutput("databaseName", "${google_sql_database.app.name}");
  }

  protected async configure(): Promise<void> { this.log("Cloud SQL configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud SQL: running migrations"); }
  protected async validate(): Promise<void> { this.log("Cloud SQL connectivity check"); }
  protected async doRollback(): Promise<void> { this.log("Cloud SQL rollback: terraform destroy"); }
}
