import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class CloudTasksAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const region = this.context.plan.region;
    const cfg = this.context.recommendation.config as {
      queueName?: string;
      maxConcurrent?: number;
      maxDispatchesPerSecond?: number;
      maxAttempts?: number;
    };

    const queueName = cfg.queueName ?? `${projectName}-queue`;
    const maxConcurrent = cfg.maxConcurrent ?? 100;
    const maxDispatch = cfg.maxDispatchesPerSecond ?? 100;
    const maxAttempts = cfg.maxAttempts ?? 5;

    const tf = `# Cloud Tasks — Generated by Launch Platform
resource "google_cloud_tasks_queue" "main" {
  project  = "${projectId}"
  name     = "${queueName}"
  location = "${region}"

  rate_limits {
    max_concurrent_dispatches = ${maxConcurrent}
    max_dispatches_per_second = ${maxDispatch}
  }

  retry_config {
    max_attempts       = ${maxAttempts}
    min_backoff        = "1s"
    max_backoff        = "300s"
    max_doublings      = 16
    max_retry_duration = "600s"
  }

  stackdriver_logging_config {
    sampling_ratio = 1.0
  }
}

output "queue_name" { value = google_cloud_tasks_queue.main.name }
output "queue_id"   { value = google_cloud_tasks_queue.main.id }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("queueName", "${google_cloud_tasks_queue.main.name}");
    this.publishOutput("queueId", "${google_cloud_tasks_queue.main.id}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Tasks configured"); }
  protected async deploy(): Promise<void>   { this.log("Cloud Tasks deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("Cloud Tasks queue ready"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Tasks rollback"); }

  async stop() {
    this.log("Cloud Tasks stop: pause via 'gcloud tasks queues pause'");
    return { success: false, outputs: {}, error: "stop() requires gcloud tasks queues pause" };
  }
}
