import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class CloudBuildAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const cfg = this.context.recommendation.config as {
      githubOwner?: string;
      githubRepo?: string;
      branchPattern?: string;
      filename?: string;
    };

    const branch = cfg.branchPattern ?? "^main$";
    const filename = cfg.filename ?? "cloudbuild.yaml";

    const triggerBlock = (cfg.githubOwner && cfg.githubRepo)
      ? `github {
    owner = "${cfg.githubOwner}"
    name  = "${cfg.githubRepo}"
    push {
      branch = "${branch}"
    }
  }`
      : `# No GitHub config provided. Trigger left as manual-only.
  # Provide config.githubOwner + config.githubRepo to enable push triggers.`;

    const tf = `# Cloud Build — Generated by Launch Platform
resource "google_cloudbuild_trigger" "main" {
  project     = "${projectId}"
  name        = "${projectName}-build"
  description = "Auto-build trigger for ${projectName}"

  ${triggerBlock}

  filename = "${filename}"

  substitutions = {
    _PROJECT_NAME = "${projectName}"
  }
}

output "trigger_id"   { value = google_cloudbuild_trigger.main.trigger_id }
output "trigger_name" { value = google_cloudbuild_trigger.main.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("triggerId", "${google_cloudbuild_trigger.main.trigger_id}");
    this.publishOutput("triggerName", "${google_cloudbuild_trigger.main.name}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Build configured"); }
  protected async deploy(): Promise<void>   { this.log("Cloud Build deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("Cloud Build trigger active"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Build rollback"); }

  async stop() {
    this.log("Cloud Build stop: disable trigger via terraform re-apply with disabled=true");
    return { success: false, outputs: {}, error: "stop() requires terraform re-apply with disabled=true" };
  }
}
