import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class CloudLBAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("vpc-gcp", "networkName");
    const projectName = this.getProjectName();
    const region = this.context.plan.region;
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Cloud Load Balancer — Generated by SASA Launch
resource "google_compute_region_network_endpoint_group" "app" {
  name                  = "${projectName}-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "${region}"
  project               = "${projectId}"

  cloud_run {
    service = var.cloud_run_service_name
  }
}

resource "google_compute_region_backend_service" "app" {
  name                  = "${projectName}-backend"
  region                = "${region}"
  project               = "${projectId}"
  protocol              = "HTTP"
  load_balancing_scheme = "EXTERNAL_MANAGED"
  timeout_sec           = 30

  backend {
    group           = google_compute_region_network_endpoint_group.app.id
    balancing_mode  = "UTILIZATION"
  }

  health_checks = [google_compute_region_health_check.app.id]
}

resource "google_compute_region_health_check" "app" {
  name    = "${projectName}-health-check"
  region  = "${region}"
  project = "${projectId}"

  http_health_check {
    port_specification = "USE_SERVING_PORT"
    request_path       = "/health"
  }
}

resource "google_compute_region_url_map" "app" {
  name            = "${projectName}-url-map"
  region          = "${region}"
  project         = "${projectId}"
  default_service = google_compute_region_backend_service.app.id
}

resource "google_compute_region_target_http_proxy" "app" {
  name    = "${projectName}-http-proxy"
  region  = "${region}"
  project = "${projectId}"
  url_map = google_compute_region_url_map.app.id
}

resource "google_compute_forwarding_rule" "app" {
  name                  = "${projectName}-lb-rule"
  region                = "${region}"
  project               = "${projectId}"
  ip_protocol           = "TCP"
  load_balancing_scheme = "EXTERNAL_MANAGED"
  port_range            = "80"
  target                = google_compute_region_target_http_proxy.app.id
  network               = var.network_name
}

variable "cloud_run_service_name" { type = string; default = "" }
variable "network_name" { type = string }

output "lb_ip" { value = google_compute_forwarding_rule.app.ip_address }
output "backend_service_name" { value = google_compute_region_backend_service.app.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("lbIp", "${google_compute_forwarding_rule.app.ip_address}");
    this.publishOutput("backendServiceName", "${google_compute_region_backend_service.app.name}");
  }

  protected async configure(): Promise<void> { this.log("Cloud LB configured"); }
  protected async deploy(): Promise<void> { this.log("Cloud LB routing active"); }
  protected async validate(): Promise<void> { this.log("Cloud LB health check passing"); }
  protected async doRollback(): Promise<void> { this.log("Cloud LB rollback"); }
}
