import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class CloudWorkflowsAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const region = this.context.plan.region;
    const cfg = this.context.recommendation.config as {
      workflowName?: string;
      sourceContents?: string; // YAML workflow definition
    };

    const workflowName = cfg.workflowName ?? `${projectName}-workflow`;

    const defaultSource = `main:
  params: [args]
  steps:
    - hello:
        return: \${"Hello from " + args.caller}
`;
    const source = cfg.sourceContents ?? defaultSource;
    // Escape Terraform interpolation in user-supplied YAML so $ doesn't trigger TF
    const escapedSource = source.replace(/\$\{/g, "$$${");

    const tf = `# Cloud Workflows — Generated by Launch Platform
resource "google_service_account" "workflow" {
  project      = "${projectId}"
  account_id   = "${workflowName.slice(0, 28)}-sa"
  display_name = "Service account for ${workflowName}"
}

resource "google_workflows_workflow" "main" {
  project         = "${projectId}"
  name            = "${workflowName}"
  region          = "${region}"
  description     = "Workflow for ${projectName}"
  service_account = google_service_account.workflow.email

  source_contents = <<-EOT
${escapedSource.split("\n").map(l => "    " + l).join("\n")}
  EOT
}

output "workflow_name" { value = google_workflows_workflow.main.name }
output "workflow_id"   { value = google_workflows_workflow.main.id }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("workflowName", "${google_workflows_workflow.main.name}");
    this.publishOutput("workflowId", "${google_workflows_workflow.main.id}");
  }

  protected async configure(): Promise<void> { this.log("Cloud Workflows configured"); }
  protected async deploy(): Promise<void>   { this.log("Cloud Workflows deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("Cloud Workflows reachable"); }
  protected async doRollback(): Promise<void> { this.log("Cloud Workflows rollback"); }
}
