import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

/**
 * AWS CodeBuild agent. Provisions a single CodeBuild project that builds
 * a Docker image from the source repo and pushes it to the ECR repo
 * created by ecr-agent. Triggered either by CodePipeline (when present)
 * or by GitHub webhook (when not).
 */
export class CodeBuildAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    // ECR is the typical artifact target. Tolerate it being absent — the
    // user might be building lambda zips instead.
    const ecrRepoUrl = await safeWaitFor(this, "ecr", "repositoryUrl");

    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      sourceLocation?: string; // git URL
      buildspec?: string;
      computeType?: "BUILD_GENERAL1_SMALL" | "BUILD_GENERAL1_MEDIUM" | "BUILD_GENERAL1_LARGE";
      image?: string;
      timeoutMinutes?: number;
      privilegedMode?: boolean; // needed for docker-in-docker
    };
    const sourceLocation = cfg.sourceLocation ?? "https://github.com/example/repo";
    const computeType = cfg.computeType ?? "BUILD_GENERAL1_SMALL";
    const image = cfg.image ?? "aws/codebuild/standard:7.0";
    const timeoutMinutes = cfg.timeoutMinutes ?? 30;
    const privileged = cfg.privilegedMode ?? true;

    const buildspec =
      cfg.buildspec ??
      `version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - docker build -t $IMAGE_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $IMAGE_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI:latest
  post_build:
    commands:
      - docker push $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_URI:latest
artifacts:
  files: '**/*'
`;

    const tf = `# CodeBuild Project — Generated by Launch Platform
data "aws_iam_policy_document" "codebuild_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["codebuild.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "codebuild" {
  name               = "${projectName}-codebuild-role"
  assume_role_policy = data.aws_iam_policy_document.codebuild_assume.json
}

data "aws_iam_policy_document" "codebuild_policy" {
  statement {
    actions   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
    resources = ["*"]
  }
  statement {
    actions = [
      "ecr:GetAuthorizationToken",
      "ecr:BatchCheckLayerAvailability",
      "ecr:GetDownloadUrlForLayer",
      "ecr:GetRepositoryPolicy",
      "ecr:DescribeRepositories",
      "ecr:ListImages",
      "ecr:DescribeImages",
      "ecr:BatchGetImage",
      "ecr:InitiateLayerUpload",
      "ecr:UploadLayerPart",
      "ecr:CompleteLayerUpload",
      "ecr:PutImage",
    ]
    resources = ["*"]
  }
  statement {
    actions   = ["s3:GetObject", "s3:GetObjectVersion", "s3:PutObject"]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "codebuild" {
  role   = aws_iam_role.codebuild.id
  policy = data.aws_iam_policy_document.codebuild_policy.json
}

resource "aws_codebuild_project" "this" {
  name          = "${projectName}-build"
  service_role  = aws_iam_role.codebuild.arn
  build_timeout = ${timeoutMinutes}

  artifacts { type = "NO_ARTIFACTS" }

  environment {
    compute_type    = "${computeType}"
    image           = "${image}"
    type            = "LINUX_CONTAINER"
    privileged_mode = ${privileged}

    environment_variable {
      name  = "AWS_DEFAULT_REGION"
      value = data.aws_region.current.name
    }
    environment_variable {
      name  = "ECR_URI"
      value = var.ecr_uri
    }
    environment_variable {
      name  = "IMAGE_REPO"
      value = "${projectName}"
    }
  }

  source {
    type      = "GITHUB"
    location  = "${sourceLocation}"
    buildspec = <<-BUILDSPEC
${indent(buildspec, "      ")}
BUILDSPEC
  }
}

data "aws_region" "current" {}

variable "ecr_uri" {
  type    = string
  default = "${ecrRepoUrl ?? `123456789012.dkr.ecr.us-east-1.amazonaws.com/${projectName}`}"
}

output "codebuild_project_name" { value = aws_codebuild_project.this.name }
output "codebuild_project_arn"  { value = aws_codebuild_project.this.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("projectName", "${aws_codebuild_project.this.name}");
    this.publishOutput("projectArn", "${aws_codebuild_project.this.arn}");
  }

  protected async configure(): Promise<void> { this.log("CodeBuild configured"); }
  protected async deploy(): Promise<void> { this.log("CodeBuild deploys via terraform apply"); }
  protected async validate(): Promise<void> { this.log("CodeBuild validation: codebuild:BatchGetProjects would go here"); }
  protected async doRollback(): Promise<void> { this.log("CodeBuild rollback: terraform destroy"); }
}

function indent(text: string, prefix: string): string {
  return text
    .split("\n")
    .map((l) => (l.length ? prefix + l : l))
    .join("\n");
}

/** waitFor that does not throw when the dependency is absent — useful
 * when an agent has optional upstream relationships. */
async function safeWaitFor(
  agent: DeploymentAgent,
  agentId: string,
  outputKey: string,
  timeoutMs = 5000,
): Promise<unknown | null> {
  // We can't access the protected `bus` from here, so do the wait via a
  // race against a sleep. The agent's own waitFor is not exposed; this
  // helper is a best-effort.
  const trySymbol = Symbol("timeout");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const a = agent as any;
  const promise = a.bus
    ? a.bus.waitForOutput(`${agentId}-agent`, outputKey, timeoutMs)
    : Promise.resolve(null);
  const result = await Promise.race([
    promise,
    new Promise((resolve) => setTimeout(() => resolve(trySymbol), timeoutMs)),
  ]);
  return result === trySymbol ? null : result;
}
