import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

/**
 * AWS CodePipeline agent. Provisions a 3-stage pipeline (Source → Build
 * → Deploy) wired to the codebuild-agent's project and an artifact S3
 * bucket. Source = GitHub via CodeStar Connections (the connection ARN
 * is required input).
 *
 * If the connection ARN is not supplied via config.codestarConnectionArn,
 * the pipeline still provisions but the source action will need a
 * one-time manual auth in the AWS console.
 */
export class CodePipelineAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const codebuildProject = await this.waitFor("codebuild", "projectName");

    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      githubOwner?: string;
      githubRepo?: string;
      githubBranch?: string;
      codestarConnectionArn?: string;
    };
    const owner = cfg.githubOwner ?? "your-org";
    const repo = cfg.githubRepo ?? projectName;
    const branch = cfg.githubBranch ?? "main";
    const connectionArn =
      cfg.codestarConnectionArn ??
      "arn:aws:codestar-connections:us-east-1:123456789012:connection/REPLACE_ME";

    const tf = `# CodePipeline — Generated by Launch Platform
resource "aws_s3_bucket" "artifacts" {
  bucket        = "${projectName}-pipeline-artifacts"
  force_destroy = true
}

resource "aws_s3_bucket_versioning" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  versioning_configuration { status = "Enabled" }
}

data "aws_iam_policy_document" "pipeline_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["codepipeline.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "pipeline" {
  name               = "${projectName}-pipeline-role"
  assume_role_policy = data.aws_iam_policy_document.pipeline_assume.json
}

data "aws_iam_policy_document" "pipeline_policy" {
  statement {
    actions   = ["s3:GetObject", "s3:PutObject", "s3:GetObjectVersion", "s3:GetBucketVersioning", "s3:ListBucket"]
    resources = [aws_s3_bucket.artifacts.arn, "\${aws_s3_bucket.artifacts.arn}/*"]
  }
  statement {
    actions   = ["codebuild:BatchGetBuilds", "codebuild:StartBuild"]
    resources = ["*"]
  }
  statement {
    actions   = ["codestar-connections:UseConnection"]
    resources = ["${connectionArn}"]
  }
}

resource "aws_iam_role_policy" "pipeline" {
  role   = aws_iam_role.pipeline.id
  policy = data.aws_iam_policy_document.pipeline_policy.json
}

resource "aws_codepipeline" "this" {
  name     = "${projectName}-pipeline"
  role_arn = aws_iam_role.pipeline.arn

  artifact_store {
    location = aws_s3_bucket.artifacts.bucket
    type     = "S3"
  }

  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]
      configuration = {
        ConnectionArn    = "${connectionArn}"
        FullRepositoryId = "${owner}/${repo}"
        BranchName       = "${branch}"
      }
    }
  }

  stage {
    name = "Build"
    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      version          = "1"
      input_artifacts  = ["source_output"]
      output_artifacts = ["build_output"]
      configuration = {
        ProjectName = var.codebuild_project_name
      }
    }
  }
}

variable "codebuild_project_name" {
  type    = string
  default = "${codebuildProject as string}"
}

output "pipeline_name" { value = aws_codepipeline.this.name }
output "pipeline_arn"  { value = aws_codepipeline.this.arn }
output "artifacts_bucket" { value = aws_s3_bucket.artifacts.bucket }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("pipelineName", "${aws_codepipeline.this.name}");
    this.publishOutput("pipelineArn", "${aws_codepipeline.this.arn}");
  }

  protected async configure(): Promise<void> { this.log("CodePipeline configured"); }
  protected async deploy(): Promise<void> { this.log("CodePipeline deploys via terraform apply"); }
  protected async validate(): Promise<void> { this.log("CodePipeline validation: codepipeline:GetPipelineState would go here"); }
  protected async doRollback(): Promise<void> { this.log("CodePipeline rollback: terraform destroy"); }
}
