import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class CognitoAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      passwordMinLength?: number;
      enableMFA?: boolean;
      domainPrefix?: string;
      callbackUrls?: string[];
      logoutUrls?: string[];
    };

    const minLen = cfg.passwordMinLength ?? 8;
    const callbacks = JSON.stringify(cfg.callbackUrls ?? ["http://localhost:3000/callback"]);
    const logouts = JSON.stringify(cfg.logoutUrls ?? ["http://localhost:3000"]);
    const domainBlock = cfg.domainPrefix
      ? `resource "aws_cognito_user_pool_domain" "main" {
  domain       = "${cfg.domainPrefix}-${projectName}"
  user_pool_id = aws_cognito_user_pool.main.id
}

`
      : "";

    const tf = `# Cognito User Pool — Generated by Launch Platform
resource "aws_cognito_user_pool" "main" {
  name = "${projectName}-users"

  password_policy {
    minimum_length    = ${minLen}
    require_lowercase = true
    require_uppercase = true
    require_numbers   = true
    require_symbols   = false
  }

  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]

  mfa_configuration = "${cfg.enableMFA ? "ON" : "OFF"}"
  ${cfg.enableMFA ? `software_token_mfa_configuration { enabled = true }` : ""}

  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
  }

  email_configuration {
    email_sending_account = "COGNITO_DEFAULT"
  }

  schema {
    name                = "email"
    attribute_data_type = "String"
    mutable             = true
    required            = true
    string_attribute_constraints { min_length = 3 max_length = 256 }
  }
}

resource "aws_cognito_user_pool_client" "main" {
  name                          = "${projectName}-client"
  user_pool_id                  = aws_cognito_user_pool.main.id
  generate_secret               = false
  prevent_user_existence_errors = "ENABLED"

  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  callback_urls = ${callbacks}
  logout_urls   = ${logouts}

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_scopes                 = ["openid", "email", "profile"]
  allowed_oauth_flows_user_pool_client = true
  supported_identity_providers         = ["COGNITO"]
}

${domainBlock}output "user_pool_id"     { value = aws_cognito_user_pool.main.id }
output "user_pool_arn"    { value = aws_cognito_user_pool.main.arn }
output "client_id"        { value = aws_cognito_user_pool_client.main.id }
${cfg.domainPrefix ? `output "domain"           { value = aws_cognito_user_pool_domain.main.domain }` : ""}
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("userPoolId", "${aws_cognito_user_pool.main.id}");
    this.publishOutput("userPoolArn", "${aws_cognito_user_pool.main.arn}");
    this.publishOutput("clientId", "${aws_cognito_user_pool_client.main.id}");
  }

  protected async configure(): Promise<void> { this.log("Cognito configured"); }
  protected async deploy(): Promise<void>   { this.log("Cognito deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("Cognito user pool active"); }
  protected async doRollback(): Promise<void> { this.log("Cognito rollback"); }
}
