import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

interface DynamoAttribute {
  name: string;
  type: "S" | "N" | "B";
}

interface DynamoGSI {
  name: string;
  hashKey: string;
  rangeKey?: string;
  projectionType?: "ALL" | "KEYS_ONLY" | "INCLUDE";
  nonKeyAttributes?: string[];
}

export class DynamoDBAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      tableName?: string;
      hashKey?: string;
      rangeKey?: string;
      attributes?: DynamoAttribute[];
      globalSecondaryIndexes?: DynamoGSI[];
      ttlAttribute?: string;
    };

    const tableName = cfg.tableName ?? `${projectName}-table`;
    const hashKey = cfg.hashKey ?? "id";
    const rangeKey = cfg.rangeKey;

    // Build attribute set: hash, range, and any GSI keys must be declared.
    const attrSet = new Map<string, DynamoAttribute>();
    const addAttr = (name: string, type: DynamoAttribute["type"] = "S") => {
      if (!attrSet.has(name)) attrSet.set(name, { name, type });
    };
    addAttr(hashKey, "S");
    if (rangeKey) addAttr(rangeKey, "S");
    for (const a of cfg.attributes ?? []) addAttr(a.name, a.type);
    for (const gsi of cfg.globalSecondaryIndexes ?? []) {
      addAttr(gsi.hashKey, "S");
      if (gsi.rangeKey) addAttr(gsi.rangeKey, "S");
    }

    const attrBlocks = [...attrSet.values()].map((a) =>
      `  attribute {\n    name = "${a.name}"\n    type = "${a.type}"\n  }`
    ).join("\n");

    const gsiBlocks = (cfg.globalSecondaryIndexes ?? []).map((gsi) => {
      const range = gsi.rangeKey ? `\n    range_key       = "${gsi.rangeKey}"` : "";
      const projType = gsi.projectionType ?? "ALL";
      const nonKey = projType === "INCLUDE" && gsi.nonKeyAttributes?.length
        ? `\n    non_key_attributes = ${JSON.stringify(gsi.nonKeyAttributes)}`
        : "";
      return `  global_secondary_index {
    name            = "${gsi.name}"
    hash_key        = "${gsi.hashKey}"${range}
    projection_type = "${projType}"${nonKey}
  }`;
    }).join("\n");

    const ttlBlock = cfg.ttlAttribute
      ? `
  ttl {
    attribute_name = "${cfg.ttlAttribute}"
    enabled        = true
  }`
      : "";

    const tf = `# DynamoDB — Generated by Launch Platform
resource "aws_dynamodb_table" "main" {
  name         = "${tableName}"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "${hashKey}"${rangeKey ? `\n  range_key    = "${rangeKey}"` : ""}

${attrBlocks}

${gsiBlocks}

  point_in_time_recovery {
    enabled = true
  }

  server_side_encryption {
    enabled = true
  }${ttlBlock}

  tags = {
    Name    = "${tableName}"
    Project = "${projectName}"
  }
}

output "table_name" { value = aws_dynamodb_table.main.name }
output "table_arn"  { value = aws_dynamodb_table.main.arn }
output "stream_arn" { value = aws_dynamodb_table.main.stream_arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("tableName", "${aws_dynamodb_table.main.name}");
    this.publishOutput("tableArn", "${aws_dynamodb_table.main.arn}");
    this.publishOutput("streamArn", "${aws_dynamodb_table.main.stream_arn}");
  }

  protected async configure(): Promise<void> { this.log("DynamoDB configured"); }
  protected async deploy(): Promise<void>   { this.log("DynamoDB deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("DynamoDB table active"); }
  protected async doRollback(): Promise<void> { this.log("DynamoDB rollback: terraform destroy"); }
}
