import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class EC2Agent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const vpcId = await this.waitFor("vpc", "vpcId");
    const sgId = await this.waitFor("vpc", "securityGroupId");
    const projectName = this.getProjectName();

    const tf = `# EC2 Configuration — Generated by Launch Platform
data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}

resource "aws_instance" "app" {
  ami                    = data.aws_ami.amazon_linux.id
  instance_type          = "t3.micro"
  subnet_id              = ${JSON.stringify(vpcId)} # Reference from VPC module
  vpc_security_group_ids = [${JSON.stringify(sgId)}]

  user_data = <<-EOF
    #!/bin/bash
    yum update -y
    yum install -y docker
    systemctl start docker
    systemctl enable docker
  EOF

  tags = { Name = "${projectName}-app" }
}

output "instance_id" { value = aws_instance.app.id }
output "public_ip" { value = aws_instance.app.public_ip }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("instanceId", "${aws_instance.app.id}");
    this.publishOutput("publicIp", "${aws_instance.app.public_ip}");
  }

  protected async configure(): Promise<void> { this.log("EC2 configured"); }
  protected async deploy(): Promise<void> { this.log("EC2 application deployment"); }
  protected async validate(): Promise<void> { this.log("EC2 health check"); }
  protected async doRollback(): Promise<void> { this.log("EC2 rollback: terraform destroy"); }
}
