import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

/**
 * EKS (Elastic Kubernetes Service) agent. Provisions a small managed
 * cluster + a single managed node group. Production-sane defaults but
 * minimal: one node group, public+private endpoint, kms-encrypted
 * secrets disabled by default for simplicity (toggle via config).
 */
export class EKSAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const vpcId = await this.waitFor("vpc", "vpcId");
    const privateSubnetIdsCsv = await this.waitFor("vpc", "privateSubnetIds");

    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      kubernetesVersion?: string;
      nodeInstanceType?: string;
      desiredNodes?: number;
      minNodes?: number;
      maxNodes?: number;
      enableSecretsEncryption?: boolean;
    };
    const k8sVersion = cfg.kubernetesVersion ?? "1.30";
    const nodeType = cfg.nodeInstanceType ?? "t3.medium";
    const desired = cfg.desiredNodes ?? 2;
    const minNodes = cfg.minNodes ?? 1;
    const maxNodes = cfg.maxNodes ?? 4;

    const tf = `# EKS Cluster — Generated by Launch Platform
data "aws_iam_policy_document" "eks_cluster_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["eks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "eks_cluster" {
  name               = "${projectName}-eks-cluster-role"
  assume_role_policy = data.aws_iam_policy_document.eks_cluster_assume.json
}

resource "aws_iam_role_policy_attachment" "eks_cluster_policy" {
  role       = aws_iam_role.eks_cluster.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
}

data "aws_iam_policy_document" "eks_node_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "eks_node" {
  name               = "${projectName}-eks-node-role"
  assume_role_policy = data.aws_iam_policy_document.eks_node_assume.json
}

resource "aws_iam_role_policy_attachment" "eks_node_worker_policy" {
  role       = aws_iam_role.eks_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
}

resource "aws_iam_role_policy_attachment" "eks_node_cni_policy" {
  role       = aws_iam_role.eks_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
}

resource "aws_iam_role_policy_attachment" "eks_node_ecr_read" {
  role       = aws_iam_role.eks_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
}

resource "aws_eks_cluster" "this" {
  name     = "${projectName}-cluster"
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "${k8sVersion}"

  vpc_config {
    subnet_ids              = split(",", var.private_subnet_ids)
    endpoint_private_access = true
    endpoint_public_access  = true
  }

  depends_on = [aws_iam_role_policy_attachment.eks_cluster_policy]
}

resource "aws_eks_node_group" "default" {
  cluster_name    = aws_eks_cluster.this.name
  node_group_name = "default"
  node_role_arn   = aws_iam_role.eks_node.arn
  subnet_ids      = split(",", var.private_subnet_ids)
  instance_types  = ["${nodeType}"]

  scaling_config {
    desired_size = ${desired}
    min_size     = ${minNodes}
    max_size     = ${maxNodes}
  }

  update_config {
    max_unavailable = 1
  }

  depends_on = [
    aws_iam_role_policy_attachment.eks_node_worker_policy,
    aws_iam_role_policy_attachment.eks_node_cni_policy,
    aws_iam_role_policy_attachment.eks_node_ecr_read,
  ]
}

variable "vpc_id"             { type = string }
variable "private_subnet_ids" { type = string }

output "cluster_name"     { value = aws_eks_cluster.this.name }
output "cluster_endpoint" { value = aws_eks_cluster.this.endpoint }
output "cluster_arn"      { value = aws_eks_cluster.this.arn }
output "node_role_arn"    { value = aws_iam_role.eks_node.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    void vpcId;
    void privateSubnetIdsCsv;
    this.publishOutput("clusterName", "${aws_eks_cluster.this.name}");
    this.publishOutput("clusterEndpoint", "${aws_eks_cluster.this.endpoint}");
    this.publishOutput("clusterArn", "${aws_eks_cluster.this.arn}");
  }

  protected async configure(): Promise<void> { this.log("EKS configured"); }
  protected async deploy(): Promise<void> { this.log("EKS deploys via terraform apply"); }
  protected async validate(): Promise<void> { this.log("EKS validation: kubectl get nodes would go here"); }
  protected async doRollback(): Promise<void> { this.log("EKS rollback: terraform destroy"); }
}
