import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class EventBridgeAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      schedule?: string;          // e.g. "rate(5 minutes)" or "cron(0 12 * * ? *)"
      eventPattern?: string;      // JSON string for event-pattern rules
      targetType?: "lambda" | "sqs" | "sns";
      ruleName?: string;
    };

    const ruleName = cfg.ruleName ?? `${projectName}-rule`;
    const schedule = cfg.schedule ?? "rate(1 hour)";
    const targetType = cfg.targetType ?? "lambda";

    const wantsLambdaTarget = targetType === "lambda" && this.dependencies.includes("lambda");
    if (wantsLambdaTarget) {
      await this.waitFor("lambda", "functionArn");
      await this.waitFor("lambda", "functionName");
    }
    const wantsSqsTarget = targetType === "sqs" && this.dependencies.includes("sqs");
    if (wantsSqsTarget) {
      await this.waitFor("sqs", "queueArn");
    }

    const ruleBlock = cfg.eventPattern
      ? `resource "aws_cloudwatch_event_rule" "main" {
  name          = "${ruleName}"
  description   = "Event-pattern rule for ${projectName}"
  event_pattern = jsonencode(${cfg.eventPattern})
  state         = "ENABLED"
}`
      : `resource "aws_cloudwatch_event_rule" "main" {
  name                = "${ruleName}"
  description         = "Scheduled rule for ${projectName}"
  schedule_expression = "${schedule}"
  state               = "ENABLED"
}`;

    const targetBlock = wantsLambdaTarget
      ? `resource "aws_cloudwatch_event_target" "lambda" {
  rule      = aws_cloudwatch_event_rule.main.name
  target_id = "lambda"
  arn       = aws_lambda_function.app.arn
}

resource "aws_lambda_permission" "events" {
  statement_id  = "AllowExecutionFromEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.app.function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.main.arn
}`
      : wantsSqsTarget
      ? `resource "aws_cloudwatch_event_target" "sqs" {
  rule      = aws_cloudwatch_event_rule.main.name
  target_id = "sqs"
  arn       = aws_sqs_queue.main.arn
}`
      : `# No target dependency wired. Add a target manually for production use.`;

    const tf = `# EventBridge — Generated by Launch Platform
${ruleBlock}

${targetBlock}

output "rule_name" { value = aws_cloudwatch_event_rule.main.name }
output "rule_arn"  { value = aws_cloudwatch_event_rule.main.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("ruleName", "${aws_cloudwatch_event_rule.main.name}");
    this.publishOutput("ruleArn", "${aws_cloudwatch_event_rule.main.arn}");
  }

  protected async configure(): Promise<void> { this.log("EventBridge configured"); }
  protected async deploy(): Promise<void>   { this.log("EventBridge deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("EventBridge rule enabled"); }
  protected async doRollback(): Promise<void> { this.log("EventBridge rollback"); }

  async stop() {
    this.log("EventBridge stop: re-apply with state = DISABLED on the rule");
    return { success: false, outputs: {}, error: "stop() requires terraform re-apply with state=DISABLED" };
  }
}
