import { copyFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { DeploymentAgent } from "../agent-base";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RULES_TEMPLATE = join(__dirname, "..", "..", "templates", "firestore", "firestore.rules");

interface FirestoreIndexConfig {
  collection: string;
  queryScope?: "COLLECTION" | "COLLECTION_GROUP";
  fields: { fieldPath: string; order?: "ASCENDING" | "DESCENDING"; arrayConfig?: "CONTAINS" }[];
}

export class FirestoreAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const region = this.context.plan.region;
    const cfg = this.context.recommendation.config as {
      indexes?: FirestoreIndexConfig[];
      rulesPath?: string;
    };

    // Stage rules file alongside main.tf so the merged stack can read it
    const rulesDest = join(this.context.artifactDir, "firestore.rules");
    if (cfg.rulesPath) {
      copyFileSync(cfg.rulesPath, rulesDest);
      this.log(`Firestore rules sourced from ${cfg.rulesPath}`);
    } else {
      copyFileSync(RULES_TEMPLATE, rulesDest);
      this.log("Firestore default-deny rules staged (override via config.rulesPath)");
    }

    const indexResources = (cfg.indexes ?? []).map((idx, i) => {
      const fieldsBlock = idx.fields.map((f) => {
        const parts = [`field_path = "${f.fieldPath}"`];
        if (f.order) parts.push(`order      = "${f.order}"`);
        if (f.arrayConfig) parts.push(`array_config = "${f.arrayConfig}"`);
        return `  fields {\n    ${parts.join("\n    ")}\n  }`;
      }).join("\n");

      return `resource "google_firestore_index" "idx_${i}" {
  project     = "${projectId}"
  collection  = "${idx.collection}"
  query_scope = "${idx.queryScope ?? "COLLECTION"}"
${fieldsBlock}

  depends_on = [google_firestore_database.main]
}`;
    }).join("\n\n");

    const tf = `# Firestore — Generated by Launch Platform
resource "google_firestore_database" "main" {
  project                     = "${projectId}"
  name                        = "(default)"
  location_id                 = "${region}"
  type                        = "FIRESTORE_NATIVE"
  concurrency_mode            = "OPTIMISTIC"
  app_engine_integration_mode = "DISABLED"
  point_in_time_recovery_enablement = "POINT_IN_TIME_RECOVERY_ENABLED"
  delete_protection_state     = "DELETE_PROTECTION_DISABLED"
}

# Default-deny security rules. Edit firestore.rules in the artifact dir.
resource "google_firebaserules_ruleset" "primary" {
  project = "${projectId}"

  source {
    files {
      name    = "firestore.rules"
      content = file("\${path.module}/firestore.rules")
    }
  }
}

resource "google_firebaserules_release" "primary" {
  project      = "${projectId}"
  name         = "cloud.firestore"
  ruleset_name = "projects/${projectId}/rulesets/\${google_firebaserules_ruleset.primary.name}"

  depends_on = [google_firestore_database.main]
}

${indexResources}

output "database_name" { value = google_firestore_database.main.name }
output "rules_release" { value = google_firebaserules_release.primary.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("databaseName", "${google_firestore_database.main.name}");
    this.publishOutput("rulesRelease", "${google_firebaserules_release.primary.name}");
  }

  protected async configure(): Promise<void> { this.log("Firestore configured"); }
  protected async deploy(): Promise<void>   { this.log("Firestore deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("Firestore reachable"); }
  protected async doRollback(): Promise<void> { this.log("Firestore rollback: terraform destroy"); }
}
