import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class IAMAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();

    const tf = `# IAM Configuration — Generated by Launch Platform
resource "aws_iam_role" "ecs_execution" {
  name = "${projectName}-ecs-execution"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role       = aws_iam_role.ecs_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role" "ecs_task" {
  name = "${projectName}-ecs-task"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role" "lambda_execution" {
  name = "${projectName}-lambda-execution"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

output "ecs_execution_role_arn" { value = aws_iam_role.ecs_execution.arn }
output "ecs_task_role_arn" { value = aws_iam_role.ecs_task.arn }
output "lambda_execution_role_arn" { value = aws_iam_role.lambda_execution.arn }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.log("Generated IAM Terraform configuration");

    this.publishOutput("ecsExecutionRoleArn", "${aws_iam_role.ecs_execution.arn}");
    this.publishOutput("ecsTaskRoleArn", "${aws_iam_role.ecs_task.arn}");
    this.publishOutput("lambdaExecutionRoleArn", "${aws_iam_role.lambda_execution.arn}");
  }

  protected async configure(): Promise<void> { this.log("IAM configured"); }
  protected async deploy(): Promise<void> { this.log("IAM deployed via Terraform"); }
  protected async validate(): Promise<void> { this.log("IAM roles validated"); }
  protected async doRollback(): Promise<void> { this.log("IAM rollback: terraform destroy"); }
}
