import { copyFileSync, mkdirSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { DeploymentAgent } from "../agent-base";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLACEHOLDER_SRC = join(__dirname, "..", "..", "templates", "lambda", "index.js");

export class LambdaAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    await this.waitFor("iam", "lambdaExecutionRoleArn");
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      codeS3Bucket?: string;
      codeS3Key?: string;
      memorySize?: number;
      timeout?: number;
      reservedConcurrency?: number;
    };

    let codeBlock: string;
    if (cfg.codeS3Bucket && cfg.codeS3Key) {
      // User supplied an S3 object — use it directly.
      codeBlock = `s3_bucket = "${cfg.codeS3Bucket}"
  s3_key    = "${cfg.codeS3Key}"`;
    } else {
      // Default: ship a placeholder handler. Stage the source under
      // <artifactDir>/lambda_src/ and let terraform's archive_file build a zip.
      const srcDir = join(this.context.artifactDir, "lambda_src");
      mkdirSync(srcDir, { recursive: true });
      copyFileSync(PLACEHOLDER_SRC, join(srcDir, "index.js"));
      this.log("Lambda placeholder source staged at lambda_src/index.js");

      codeBlock = `filename         = data.archive_file.code.output_path
  source_code_hash = data.archive_file.code.output_base64sha256`;
    }

    const archiveBlock = (cfg.codeS3Bucket && cfg.codeS3Key)
      ? ""
      : `data "archive_file" "code" {
  type        = "zip"
  source_dir  = "\${path.module}/lambda_src"
  output_path = "\${path.module}/lambda.zip"
}

`;

    const memorySize = cfg.memorySize ?? 256;
    const timeout = cfg.timeout ?? 30;
    const reservedConcurrency = cfg.reservedConcurrency ?? -1; // -1 = unset

    const tf = `# Lambda Configuration — Generated by Launch Platform
${archiveBlock}resource "aws_lambda_function" "app" {
  function_name = "${projectName}-function"
  runtime       = "nodejs20.x"
  handler       = "index.handler"
  role          = var.lambda_execution_role_arn
  memory_size   = ${memorySize}
  timeout       = ${timeout}
  ${codeBlock}

  ${reservedConcurrency >= 0 ? `reserved_concurrent_executions = var.reserved_concurrency` : ""}

  environment {
    variables = { NODE_ENV = "production" }
  }
}

resource "aws_lambda_function_url" "app" {
  function_name      = aws_lambda_function.app.function_name
  authorization_type = "NONE"
}

variable "lambda_execution_role_arn" { type = string }
${reservedConcurrency >= 0 ? `variable "reserved_concurrency" {
  type    = number
  default = ${reservedConcurrency}
}` : ""}

output "function_arn"  { value = aws_lambda_function.app.arn }
output "function_url"  { value = aws_lambda_function_url.app.function_url }
output "function_name" { value = aws_lambda_function.app.function_name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("functionArn", "${aws_lambda_function.app.arn}");
    this.publishOutput("functionUrl", "${aws_lambda_function_url.app.function_url}");
    this.publishOutput("functionName", "${aws_lambda_function.app.function_name}");
  }

  protected async configure(): Promise<void> { this.log("Lambda configured"); }
  protected async deploy(): Promise<void>   { this.log("Lambda deploys via terraform apply"); }
  protected async validate(): Promise<void> { this.log("Lambda validation: invoke check would go here"); }
  protected async doRollback(): Promise<void> { this.log("Lambda rollback: terraform destroy"); }

  // Lambda's pause-equivalent: set reserved concurrency to 0.
  async stop() {
    this.log("Lambda stop: setting reserved concurrency to 0 (manual: terraform apply with reservedConcurrency=0)");
    return { success: false, outputs: {}, error: "stop() requires terraform re-apply with reservedConcurrency=0" };
  }
}
