import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class OpenSearchAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      engineVersion?: string;
      instanceType?: string;
      instanceCount?: number;
      volumeSize?: number;
      multiAz?: boolean;
      masterUserName?: string;
    };

    const engineVersion = cfg.engineVersion ?? "OpenSearch_2.13";
    const instanceType = cfg.instanceType ?? "t3.small.search";
    const instanceCount = cfg.instanceCount ?? 1;
    const volumeSize = cfg.volumeSize ?? 10;
    const masterUser = cfg.masterUserName ?? "admin";

    const domainName = `${projectName.replace(/[^a-z0-9-]/g, "").slice(0, 27)}-os`.toLowerCase();

    const tf = `# OpenSearch — Generated by Launch Platform
resource "random_password" "opensearch_master" {
  length  = 24
  special = true
  override_special = "!@#$%^&*()-_=+"
}

resource "aws_opensearch_domain" "main" {
  domain_name    = "${domainName}"
  engine_version = "${engineVersion}"

  cluster_config {
    instance_type            = "${instanceType}"
    instance_count           = ${instanceCount}
    zone_awareness_enabled   = ${cfg.multiAz ?? false}
    ${cfg.multiAz ? `zone_awareness_config {
      availability_zone_count = 2
    }` : ""}
  }

  ebs_options {
    ebs_enabled = true
    volume_type = "gp3"
    volume_size = ${volumeSize}
  }

  encrypt_at_rest         { enabled = true }
  node_to_node_encryption { enabled = true }

  domain_endpoint_options {
    enforce_https       = true
    tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
  }

  advanced_security_options {
    enabled                        = true
    internal_user_database_enabled = true
    master_user_options {
      master_user_name     = "${masterUser}"
      master_user_password = random_password.opensearch_master.result
    }
  }

  access_policies = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "*" }
      Action    = "es:*"
      Resource  = "arn:aws:es:*:*:domain/${domainName}/*"
    }]
  })

  tags = { Name = "${projectName}-opensearch" }
}

output "endpoint"      { value = aws_opensearch_domain.main.endpoint }
output "kibana_endpoint" { value = aws_opensearch_domain.main.dashboard_endpoint }
output "domain_arn"    { value = aws_opensearch_domain.main.arn }
output "master_username" { value = "${masterUser}" }
output "master_password" {
  value     = random_password.opensearch_master.result
  sensitive = true
}
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("endpoint", "${aws_opensearch_domain.main.endpoint}");
    this.publishOutput("domainArn", "${aws_opensearch_domain.main.arn}");
  }

  protected async configure(): Promise<void> { this.log("OpenSearch configured"); }
  protected async deploy(): Promise<void>   { this.log("OpenSearch deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("OpenSearch domain reachable"); }
  protected async doRollback(): Promise<void> { this.log("OpenSearch rollback"); }
}
