import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class PubSubAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId || "your-project-id";

    const tf = `# Pub/Sub — Generated by SASA Launch
resource "google_pubsub_topic" "main" {
  name    = "${projectName}-events"
  project = "${projectId}"

  message_retention_duration = "86400s"
}

resource "google_pubsub_subscription" "main" {
  name    = "${projectName}-events-sub"
  topic   = google_pubsub_topic.main.id
  project = "${projectId}"

  ack_deadline_seconds       = 20
  message_retention_duration = "604800s"
  retain_acked_messages      = false

  retry_policy {
    minimum_backoff = "10s"
    maximum_backoff = "600s"
  }

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.dlq.id
    max_delivery_attempts = 5
  }
}

resource "google_pubsub_topic" "dlq" {
  name    = "${projectName}-events-dlq"
  project = "${projectId}"
}

resource "google_pubsub_subscription" "dlq" {
  name    = "${projectName}-events-dlq-sub"
  topic   = google_pubsub_topic.dlq.id
  project = "${projectId}"
}

output "topic_name" { value = google_pubsub_topic.main.name }
output "topic_id" { value = google_pubsub_topic.main.id }
output "subscription_name" { value = google_pubsub_subscription.main.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("topicName", "${google_pubsub_topic.main.name}");
    this.publishOutput("topicId", "${google_pubsub_topic.main.id}");
    this.publishOutput("subscriptionName", "${google_pubsub_subscription.main.name}");
  }

  protected async configure(): Promise<void> { this.log("Pub/Sub configured"); }
  protected async deploy(): Promise<void> { this.log("Pub/Sub ready"); }
  protected async validate(): Promise<void> { this.log("Pub/Sub topic accessible"); }
  protected async doRollback(): Promise<void> { this.log("Pub/Sub rollback"); }
}
