import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class SecretsManagerAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();

    const tf = `# Secrets Manager — Generated by SASA Launch
resource "aws_secretsmanager_secret" "app" {
  name_prefix = "${projectName}-"
  description = "Application secrets for ${projectName}"

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    NOTE = "Replace these placeholder values with real secrets"
  })
}

output "secret_arn" { value = aws_secretsmanager_secret.app.arn }
output "secret_name" { value = aws_secretsmanager_secret.app.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("secretArn", "$\{aws_secretsmanager_secret.app.arn}");
    this.publishOutput("secretName", "$\{aws_secretsmanager_secret.app.name}");
  }

  protected async configure(): Promise<void> { this.log("Secrets Manager configured"); }
  protected async deploy(): Promise<void> { this.log("Secrets Manager: populate secrets"); }
  protected async validate(): Promise<void> { this.log("Secrets Manager accessible"); }
  protected async doRollback(): Promise<void> { this.log("Secrets Manager rollback"); }
}
