import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class StepFunctionsAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const cfg = this.context.recommendation.config as {
      type?: "STANDARD" | "EXPRESS";
      definition?: object;
      logRetentionDays?: number;
    };

    const sfnType = cfg.type ?? "EXPRESS";
    const logRetention = cfg.logRetentionDays ?? 7;

    // Default definition: a no-op Pass state. Users override via config.definition
    // to wire real workflow steps (Task / Choice / Map / Parallel).
    const definition = cfg.definition ?? {
      Comment: "Generated workflow — replace with real definition",
      StartAt: "Hello",
      States: {
        Hello: {
          Type: "Pass",
          Result: "Hello from Launch Platform",
          End: true,
        },
      },
    };

    const tf = `# Step Functions — Generated by Launch Platform
resource "aws_cloudwatch_log_group" "sfn" {
  name              = "/aws/sfn/${projectName}"
  retention_in_days = ${logRetention}
}

resource "aws_iam_role" "sfn" {
  name = "${projectName}-sfn-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "states.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "sfn_inline" {
  role = aws_iam_role.sfn.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogDelivery",
          "logs:GetLogDelivery",
          "logs:UpdateLogDelivery",
          "logs:DeleteLogDelivery",
          "logs:ListLogDeliveries",
          "logs:PutResourcePolicy",
          "logs:DescribeResourcePolicies",
          "logs:DescribeLogGroups",
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = ["lambda:InvokeFunction", "sqs:SendMessage", "sns:Publish"]
        Resource = "*"
      },
    ]
  })
}

resource "aws_sfn_state_machine" "main" {
  name     = "${projectName}-workflow"
  role_arn = aws_iam_role.sfn.arn
  type     = "${sfnType}"

  definition = jsonencode(${JSON.stringify(definition, null, 2).replace(/\n/g, "\n    ")})

  logging_configuration {
    log_destination        = "\${aws_cloudwatch_log_group.sfn.arn}:*"
    include_execution_data = true
    level                  = "ALL"
  }

  tags = { Name = "${projectName}-workflow" }
}

output "state_machine_arn"  { value = aws_sfn_state_machine.main.arn }
output "state_machine_name" { value = aws_sfn_state_machine.main.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("stateMachineArn", "${aws_sfn_state_machine.main.arn}");
    this.publishOutput("stateMachineName", "${aws_sfn_state_machine.main.name}");
  }

  protected async configure(): Promise<void> { this.log("Step Functions configured"); }
  protected async deploy(): Promise<void>   { this.log("Step Functions deploys via terraform"); }
  protected async validate(): Promise<void> { this.log("State machine ready"); }
  protected async doRollback(): Promise<void> { this.log("Step Functions rollback"); }
}
