import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base";

export class VertexAIAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const projectId = this.context.plan.gcpCredentials?.projectId
      ?? process.env.GOOGLE_CLOUD_PROJECT
      ?? "your-project-id";
    const region = this.context.plan.region;
    const cfg = this.context.recommendation.config as {
      endpointName?: string;
      description?: string;
    };

    const endpointName = cfg.endpointName ?? `${projectName}-endpoint`;
    const description = cfg.description ?? `Vertex AI endpoint for ${projectName}`;

    const tf = `# Vertex AI — Generated by Launch Platform
# Creates an empty endpoint. Deploy a model to it via:
#   - the gcloud CLI (gcloud ai endpoints deploy-model)
#   - or a separate google_vertex_ai_endpoint_deployed_model resource
#
# Models live in the Vertex AI Model Registry; reference an existing model
# by name or upload one via google_storage_bucket_object + custom container.

resource "google_vertex_ai_endpoint" "main" {
  project     = "${projectId}"
  name        = "${endpointName}"
  display_name = "${endpointName}"
  location    = "${region}"
  description = "${description}"

  labels = {
    project = "${projectName}"
  }
}

output "endpoint_id"   { value = google_vertex_ai_endpoint.main.id }
output "endpoint_name" { value = google_vertex_ai_endpoint.main.name }
output "endpoint_url"  {
  value = "https://${region}-aiplatform.googleapis.com/v1/projects/${projectId}/locations/${region}/endpoints/\${google_vertex_ai_endpoint.main.name}"
}
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("endpointId", "${google_vertex_ai_endpoint.main.id}");
    this.publishOutput("endpointName", "${google_vertex_ai_endpoint.main.name}");
  }

  protected async configure(): Promise<void> { this.log("Vertex AI endpoint created"); }
  protected async deploy(): Promise<void>   { this.log("Deploy a model via gcloud ai endpoints deploy-model"); }
  protected async validate(): Promise<void> { this.log("Vertex AI endpoint reachable"); }
  protected async doRollback(): Promise<void> { this.log("Vertex AI rollback"); }

  async stop() {
    this.log("Vertex AI stop: undeploy any deployed models to scale to zero");
    return { success: false, outputs: {}, error: "stop() requires undeploying models manually" };
  }
}
