import { writeFileSync } from "fs";
import { join } from "path";
import { DeploymentAgent } from "../agent-base.js";

export class VPCGCPAgent extends DeploymentAgent {
  protected async provision(): Promise<void> {
    const projectName = this.getProjectName();
    const region = this.context.plan.region;

    const tf = `# GCP VPC Network — Generated by SASA Launch
resource "google_compute_network" "main" {
  name                    = "${projectName}-vpc"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "public" {
  name          = "${projectName}-public"
  ip_cidr_range = "10.0.1.0/24"
  region        = "${region}"
  network       = google_compute_network.main.id
}

resource "google_compute_subnetwork" "private" {
  name          = "${projectName}-private"
  ip_cidr_range = "10.0.10.0/24"
  region        = "${region}"
  network       = google_compute_network.main.id

  private_ip_google_access = true
}

resource "google_compute_router" "main" {
  name    = "${projectName}-router"
  region  = "${region}"
  network = google_compute_network.main.id
}

resource "google_compute_router_nat" "main" {
  name                               = "${projectName}-nat"
  router                             = google_compute_router.main.name
  region                             = "${region}"
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
}

resource "google_compute_firewall" "allow_http" {
  name    = "${projectName}-allow-http"
  network = google_compute_network.main.name

  allow {
    protocol = "tcp"
    ports    = ["80", "443", "8080"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["web"]
}

resource "google_compute_firewall" "allow_internal" {
  name    = "${projectName}-allow-internal"
  network = google_compute_network.main.name

  allow {
    protocol = "tcp"
    ports    = ["0-65535"]
  }
  allow {
    protocol = "udp"
    ports    = ["0-65535"]
  }
  allow {
    protocol = "icmp"
  }

  source_ranges = ["10.0.0.0/16"]
}

output "network_name" { value = google_compute_network.main.name }
output "network_id" { value = google_compute_network.main.id }
output "public_subnet" { value = google_compute_subnetwork.public.name }
output "private_subnet" { value = google_compute_subnetwork.private.name }
`;

    writeFileSync(join(this.context.artifactDir, "main.tf"), tf);
    this.publishOutput("networkName", "${google_compute_network.main.name}");
    this.publishOutput("networkId", "${google_compute_network.main.id}");
    this.publishOutput("publicSubnet", "${google_compute_subnetwork.public.name}");
    this.publishOutput("privateSubnet", "${google_compute_subnetwork.private.name}");
  }

  protected async configure(): Promise<void> { this.log("VPC network configured"); }
  protected async deploy(): Promise<void> { this.log("VPC deployed via Terraform"); }
  protected async validate(): Promise<void> { this.log("VPC network validated"); }
  protected async doRollback(): Promise<void> { this.log("VPC rollback: terraform destroy"); }
}
